<!DOCTYPE html>












  


<html class="theme-next gemini use-motion" lang="zh-TW">
<head>
  <meta charset="UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=2"/>
<meta name="theme-color" content="#222">












<meta http-equiv="Cache-Control" content="no-transform" />
<meta http-equiv="Cache-Control" content="no-siteapp" />



















  
  
  
  

  
    
    
  

  

  

  

  

  
    
    
    <link href="//fonts.googleapis.com/css?family=Lato:300,300italic,400,400italic,700,700italic&subset=latin,latin-ext" rel="stylesheet" type="text/css">
  






<link href="/lib/font-awesome/css/font-awesome.min.css?v=4.6.2" rel="stylesheet" type="text/css" />

<link href="/css/main.css?v=6.4.0" rel="stylesheet" type="text/css" />


  <link rel="apple-touch-icon" sizes="180x180" href="/images/apple-touch-icon-next.png?v=6.4.0">


  <link rel="icon" type="image/png" sizes="32x32" href="/images/favicon-32x32-next.png?v=6.4.0">


  <link rel="icon" type="image/png" sizes="16x16" href="/images/favicon-16x16-next.png?v=6.4.0">


  <link rel="mask-icon" href="/images/logo.svg?v=6.4.0" color="#222">









<script type="text/javascript" id="hexo.configurations">
  var NexT = window.NexT || {};
  var CONFIG = {
    root: '/',
    scheme: 'Gemini',
    version: '6.4.0',
    sidebar: {"position":"right","display":"post","offset":12,"b2t":false,"scrollpercent":false,"onmobile":false},
    fancybox: false,
    fastclick: false,
    lazyload: false,
    tabs: true,
    motion: {"enable":true,"async":false,"transition":{"post_block":"fadeIn","post_header":"slideDownIn","post_body":"slideDownIn","coll_header":"slideLeftIn","sidebar":"slideUpIn"}},
    algolia: {
      applicationID: '',
      apiKey: '',
      indexName: '',
      hits: {"per_page":10},
      labels: {"input_placeholder":"Search for Posts","hits_empty":"We didn't find any results for the search: ${query}","hits_stats":"${hits} results found in ${time} ms"}
    }
  };
</script>


  




  <meta name="description" content="异常处理 Exception错误 Error 逻辑错误：算法写错了，加法写成了减法 笔误：变量名写错了，语法错误 函数或类使用错误，其实这也属于逻辑错误 总之，错误是可以避免的 异常 Exception 本意就是意外情况 这有个前提，没有出现上面说的错误，也就是说程序写的没有问题，但是在某些情况下，会出现一些意外，导致程序无法正常的执行下去 例如open函数操作一个文件，文件不存在，或者创建一个文">
<meta name="keywords" content="python异常处理">
<meta property="og:type" content="article">
<meta property="og:title" content="python基础学习-异常处理">
<meta property="og:url" content="http://yoursite.com/2020/05/04/python基础学习-异常处理/index.html">
<meta property="og:site_name" content="ruopu&#39;s blog">
<meta property="og:description" content="异常处理 Exception错误 Error 逻辑错误：算法写错了，加法写成了减法 笔误：变量名写错了，语法错误 函数或类使用错误，其实这也属于逻辑错误 总之，错误是可以避免的 异常 Exception 本意就是意外情况 这有个前提，没有出现上面说的错误，也就是说程序写的没有问题，但是在某些情况下，会出现一些意外，导致程序无法正常的执行下去 例如open函数操作一个文件，文件不存在，或者创建一个文">
<meta property="og:locale" content="zh-TW">
<meta property="og:updated_time" content="2020-07-30T01:26:31.988Z">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="python基础学习-异常处理">
<meta name="twitter:description" content="异常处理 Exception错误 Error 逻辑错误：算法写错了，加法写成了减法 笔误：变量名写错了，语法错误 函数或类使用错误，其实这也属于逻辑错误 总之，错误是可以避免的 异常 Exception 本意就是意外情况 这有个前提，没有出现上面说的错误，也就是说程序写的没有问题，但是在某些情况下，会出现一些意外，导致程序无法正常的执行下去 例如open函数操作一个文件，文件不存在，或者创建一个文">






  <link rel="canonical" href="http://yoursite.com/2020/05/04/python基础学习-异常处理/"/>



<script type="text/javascript" id="page.configurations">
  CONFIG.page = {
    sidebar: "",
  };
</script>

  <title>python基础学习-异常处理 | ruopu's blog</title>
  









  <noscript>
  <style type="text/css">
    .use-motion .motion-element,
    .use-motion .brand,
    .use-motion .menu-item,
    .sidebar-inner,
    .use-motion .post-block,
    .use-motion .pagination,
    .use-motion .comments,
    .use-motion .post-header,
    .use-motion .post-body,
    .use-motion .collection-title { opacity: initial; }

    .use-motion .logo,
    .use-motion .site-title,
    .use-motion .site-subtitle {
      opacity: initial;
      top: initial;
    }

    .use-motion {
      .logo-line-before i { left: initial; }
      .logo-line-after i { right: initial; }
    }
  </style>
</noscript>

</head>

<body itemscope itemtype="http://schema.org/WebPage" lang="zh-TW">

  
  
    
  

  <div class="container sidebar-position-right page-post-detail">
    <div class="headband"></div>

    <header id="header" class="header" itemscope itemtype="http://schema.org/WPHeader">
      <div class="header-inner"><div class="site-brand-wrapper">
  <div class="site-meta ">
    

    <div class="custom-logo-site-title">
      <a href="/" class="brand" rel="start">
        <span class="logo-line-before"><i></i></span>
        <span class="site-title">ruopu's blog</span>
        <span class="logo-line-after"><i></i></span>
      </a>
    </div>
    
  </div>

  <div class="site-nav-toggle">
    <button aria-label="切換導航欄">
      <span class="btn-bar"></span>
      <span class="btn-bar"></span>
      <span class="btn-bar"></span>
    </button>
  </div>
</div>



<nav class="site-nav">
  
    <ul id="menu" class="menu">
      
        
        
        
          
          <li class="menu-item menu-item-home">
    <a href="/" rel="section">
      <i class="menu-item-icon fa fa-fw fa-home"></i> <br />首頁</a>
  </li>
        
        
        
          
          <li class="menu-item menu-item-tags">
    <a href="/tags" rel="section">
      <i class="menu-item-icon fa fa-fw fa-tags"></i> <br />標籤</a>
  </li>
        
        
        
          
          <li class="menu-item menu-item-categories">
    <a href="/categories/" rel="section">
      <i class="menu-item-icon fa fa-fw fa-th"></i> <br />分類</a>
  </li>
        
        
        
          
          <li class="menu-item menu-item-archives">
    <a href="/archives/" rel="section">
      <i class="menu-item-icon fa fa-fw fa-archive"></i> <br />歸檔</a>
  </li>

      
      
        <li class="menu-item menu-item-search">
          
            <a href="javascript:;" class="popup-trigger">
          
            
              <i class="menu-item-icon fa fa-search fa-fw"></i> <br />搜尋</a>
        </li>
      
    </ul>
  

  

  
    <div class="site-search">
      
  <div class="popup search-popup local-search-popup">
  <div class="local-search-header clearfix">
    <span class="search-icon">
      <i class="fa fa-search"></i>
    </span>
    <span class="popup-btn-close">
      <i class="fa fa-times-circle"></i>
    </span>
    <div class="local-search-input-wrapper">
      <input autocomplete="off"
             placeholder="搜尋..." spellcheck="false"
             type="text" id="local-search-input">
    </div>
  </div>
  <div id="local-search-result"></div>
</div>



    </div>
  
</nav>



  



</div>
    </header>

    


    <main id="main" class="main">
      <div class="main-inner">
        <div class="content-wrap">
          
            

          
          <div id="content" class="content">
            

  <div id="posts" class="posts-expand">
    

  

  
  
  

  

  <article class="post post-type-normal" itemscope itemtype="http://schema.org/Article">
  
  
  
  <div class="post-block">
    <link itemprop="mainEntityOfPage" href="http://yoursite.com/2020/05/04/python基础学习-异常处理/">

    <span hidden itemprop="author" itemscope itemtype="http://schema.org/Person">
      <meta itemprop="name" content="ruopu">
      <meta itemprop="description" content="">
      <meta itemprop="image" content="/images/avatar.gif">
    </span>

    <span hidden itemprop="publisher" itemscope itemtype="http://schema.org/Organization">
      <meta itemprop="name" content="ruopu's blog">
    </span>

    
      <header class="post-header">

        
        
          <h1 class="post-title" itemprop="name headline">python基础学习-异常处理
              
            
          </h1>
        

        <div class="post-meta">
          <span class="post-time">

            
            
            

            
              <span class="post-meta-item-icon">
                <i class="fa fa-calendar-o"></i>
              </span>
              
                <span class="post-meta-item-text">發表於</span>
              

              
                
              

              <time title="創建時間：2020-05-04 19:09:46" itemprop="dateCreated datePublished" datetime="2020-05-04T19:09:46+08:00">2020-05-04</time>
            

            
              

              
                
                <span class="post-meta-divider">|</span>
                

                <span class="post-meta-item-icon">
                  <i class="fa fa-calendar-check-o"></i>
                </span>
                
                  <span class="post-meta-item-text">更新於</span>
                
                <time title="修改時間：2020-07-30 09:26:31" itemprop="dateModified" datetime="2020-07-30T09:26:31+08:00">2020-07-30</time>
              
            
          </span>

          
            <span class="post-category" >
            
              <span class="post-meta-divider">|</span>
            
              <span class="post-meta-item-icon">
                <i class="fa fa-folder-o"></i>
              </span>
              
                <span class="post-meta-item-text">分類於</span>
              
              
                <span itemprop="about" itemscope itemtype="http://schema.org/Thing"><a href="/categories/python/" itemprop="url" rel="index"><span itemprop="name">python</span></a></span>

                
                
              
            </span>
          

          
            
          

          
          

          
            <span class="post-meta-divider">|</span>
            <span class="post-meta-item-icon"
            >
            <i class="fa fa-eye"></i>
             閱讀次數： 
            <span class="busuanzi-value" id="busuanzi_value_page_pv" ></span>
            </span>
          

          

          

        </div>
      </header>
    

    
    
    
    <div class="post-body" itemprop="articleBody">

      
      

      
        <h3 id="异常处理-Exception"><a href="#异常处理-Exception" class="headerlink" title="异常处理 Exception"></a>异常处理 Exception</h3><p>错误 Error</p>
<p>逻辑错误：算法写错了，加法写成了减法</p>
<p>笔误：变量名写错了，语法错误</p>
<p>函数或类使用错误，其实这也属于逻辑错误</p>
<p>总之，错误是可以避免的</p>
<p>异常 Exception</p>
<p>本意就是意外情况</p>
<p>这有个前提，没有出现上面说的错误，也就是说程序写的没有问题，但是在某些情况下，会出现一些意外，导致程序无法正常的执行下去</p>
<p>例如open函数操作一个文件，文件不存在，或者创建一个文件时已经存在了，或者访问一个网络文件，突然断网了，这就是异常，是个意外的情况。</p>
<p>异常不可能避免</p>
<p>错误和异常</p>
<p>在高级编程语言中，一般都有错误和异常的概念，异常是可以捕获，并被处理的，但是错误是不能被捕获的。</p>
<p>举例</p>
<p>对比异常和错误</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">with</span> open(<span class="string">'testabc'</span>) <span class="keyword">as</span> f:</span><br><span class="line">    <span class="keyword">pass</span></span><br><span class="line"></span><br><span class="line"><span class="comment"># 异常</span></span><br><span class="line">Traceback (most recent call last):</span><br><span class="line">    File <span class="string">"test.py"</span>, line <span class="number">4</span>, <span class="keyword">in</span> &lt;module&gt;</span><br><span class="line">        <span class="keyword">with</span> open(<span class="string">'testabc'</span>) <span class="keyword">as</span> f:</span><br><span class="line">FileNotFoundError: [Errno <span class="number">2</span>] No such file <span class="keyword">or</span> directory: <span class="string">'testabc'</span></span><br><span class="line">        </span><br><span class="line"><span class="function"><span class="keyword">def</span> 0<span class="title">A</span><span class="params">()</span>:</span></span><br><span class="line">    <span class="keyword">pass</span></span><br><span class="line"></span><br><span class="line"><span class="comment"># 错误</span></span><br><span class="line">File <span class="string">"test.py"</span>, line <span class="number">3</span></span><br><span class="line">    <span class="function"><span class="keyword">def</span> 0<span class="title">A</span><span class="params">()</span>:</span></span><br><span class="line">        </span><br><span class="line">SyntaxError: invalid syntax</span><br></pre></td></tr></table></figure>
<p>一个健壮的程序</p>
<p>尽可能的避免错误</p>
<p>尽可能的捕获、处理各种异常</p>
<h3 id="产生异常"><a href="#产生异常" class="headerlink" title="产生异常"></a>产生异常</h3><p>产生：</p>
<ul>
<li>raise 语句显式的抛出异常</li>
<li>Python解释器自己检测到异常并引发它</li>
</ul>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">def</span> <span class="title">foo</span><span class="params">()</span>:</span></span><br><span class="line">    print(<span class="string">'before'</span>)</span><br><span class="line">    <span class="function"><span class="keyword">def</span> <span class="title">bar</span><span class="params">()</span>:</span></span><br><span class="line">        print(<span class="number">1</span>/<span class="number">0</span>) <span class="comment"># 除零异常</span></span><br><span class="line">        </span><br><span class="line">    bar()</span><br><span class="line">    print(<span class="string">'after'</span>)</span><br><span class="line">foo()</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">def</span> <span class="title">bar</span><span class="params">()</span>:</span></span><br><span class="line">    print(<span class="string">'before'</span>)</span><br><span class="line">    <span class="keyword">raise</span> Exception(<span class="string">'my exception'</span>)</span><br><span class="line">    print(<span class="string">'after'</span>)</span><br><span class="line">bar()</span><br></pre></td></tr></table></figure>
<p>程序会在异常抛出的地方中断执行，如果不捕获，就会提前结束程序</p>
<p>raise语句</p>
<p>raise后什么都没有，表示抛出最近一个被激活的异常，如果没有被激活的异常，则抛类型异常。这种方式很少用</p>
<p>raise后要求应该是BaseException类的子类或实例，如果是类，将被无参实例化</p>
<h3 id="异常的捕获"><a href="#异常的捕获" class="headerlink" title="异常的捕获"></a>异常的捕获</h3><figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    待捕获异常的代码块</span><br><span class="line"><span class="keyword">except</span> [异常类型]:</span><br><span class="line">    异常的处理代码块</span><br></pre></td></tr></table></figure>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    print(<span class="string">'begin'</span>)</span><br><span class="line">    c = <span class="number">1</span>/<span class="number">0</span></span><br><span class="line">    print(<span class="string">'end'</span>)</span><br><span class="line"><span class="keyword">except</span>:</span><br><span class="line">    print(<span class="string">'catch the exception'</span>)</span><br><span class="line">print(<span class="string">'outer'</span>)</span><br><span class="line">输出：</span><br><span class="line">begin</span><br><span class="line">catch the exception</span><br><span class="line">outer</span><br></pre></td></tr></table></figure>
<p>上例执行到<code>c = 1/0</code>时产生异常并抛出，由于使用了<code>try ... except</code>语句块则捕捉到了这个异常，异常生成位置之后的语句将不再执行，转而执行对应的<code>except</code>部分的语句，最后执行<code>try ... except</code>语句块之外的语句。</p>
<p>捕获指定类型的异常</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    print(<span class="string">'begin'</span>)</span><br><span class="line">    c = <span class="number">1</span>/<span class="number">0</span></span><br><span class="line">    print(<span class="string">'end'</span>)</span><br><span class="line"><span class="keyword">except</span> ArithmeticError:</span><br><span class="line">    print(<span class="string">'catch the ArithmeticError'</span>)</span><br><span class="line">print(<span class="string">'outer'</span>)</span><br><span class="line">输出：</span><br><span class="line">begin</span><br><span class="line">catch the ArithmeticError</span><br><span class="line">outer</span><br></pre></td></tr></table></figure>
<h3 id="异常类及继承层次"><a href="#异常类及继承层次" class="headerlink" title="异常类及继承层次"></a>异常类及继承层次</h3><figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br><span class="line">35</span><br><span class="line">36</span><br><span class="line">37</span><br></pre></td><td class="code"><pre><span class="line"><span class="comment"># Python异常的继承</span></span><br><span class="line"></span><br><span class="line">BaseException</span><br><span class="line"> +-- SystemExit</span><br><span class="line"> +-- KeyboardInterrupt</span><br><span class="line"> +-- GeneratorExit</span><br><span class="line"> +-- Exception</span><br><span class="line">	  +-- RuntimeError</span><br><span class="line">      		+-- RecursionError</span><br><span class="line">      +-- MemoryError</span><br><span class="line">      +-- NameError</span><br><span class="line">      +-- StopIteration</span><br><span class="line">      +-- StopAsyncIteration</span><br><span class="line">      +-- ArithmeticError</span><br><span class="line">      |    +-- FloatingPointError</span><br><span class="line">      |    +-- OverflowError</span><br><span class="line">      |    +-- ZeroDivisionError</span><br><span class="line">      +-- LookupError</span><br><span class="line">      |    +-- IndexError</span><br><span class="line">      |    +-- KeyError</span><br><span class="line">      +-- SyntaxError</span><br><span class="line">      +-- OSError</span><br><span class="line">      |    +-- BlockingIOError</span><br><span class="line">      |    +-- ChildProcessError</span><br><span class="line">      |    +-- ConnectionError</span><br><span class="line">      |    |    +-- BrokenPipeError</span><br><span class="line">      |    |    +-- ConnectionAbortedError</span><br><span class="line">      |    |    +-- ConnectionRefusedError</span><br><span class="line">      |    |    +-- ConnectionResetError</span><br><span class="line">      |    +-- FileExistsError</span><br><span class="line">      |    +-- FileNotFoundError</span><br><span class="line">      |    +-- InterrupyedError</span><br><span class="line">      |    +-- IsADirectoryError</span><br><span class="line">      |    +-- NotADirectoryError</span><br><span class="line">      |    +-- PermissionError</span><br><span class="line">      |    +-- ProcessLookupError</span><br><span class="line">      |    +-- TimeoutError</span><br></pre></td></tr></table></figure>
<h3 id="BaseException及子类"><a href="#BaseException及子类" class="headerlink" title="BaseException及子类"></a>BaseException及子类</h3><h4 id="BaseException"><a href="#BaseException" class="headerlink" title="BaseException"></a>BaseException</h4><p>所有内建异常类的基类是BaseException</p>
<h4 id="SystemExit"><a href="#SystemExit" class="headerlink" title="SystemExit"></a>SystemExit</h4><p><code>sys.exit()</code>函数引发的异常，如果异常不捕获处理，就会直接交给Python解释器，解释器退出。</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">import</span> sys</span><br><span class="line">print(<span class="string">'before'</span>)</span><br><span class="line">sys.exit(<span class="number">1</span>)</span><br><span class="line">print(<span class="string">'SysExit'</span>)</span><br><span class="line">print(<span class="string">'outer'</span>)  <span class="comment"># 是否执行？</span></span><br><span class="line">输出：</span><br><span class="line">before</span><br><span class="line"></span><br><span class="line"><span class="comment"># 捕获这个异常</span></span><br><span class="line"><span class="keyword">import</span> sys</span><br><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    sys.exit(<span class="number">1</span>)</span><br><span class="line"><span class="keyword">except</span> SystemExit:</span><br><span class="line">    print(<span class="string">'SysExit'</span>)</span><br><span class="line">print(<span class="string">'outer'</span>)  <span class="comment"># 是否执行？</span></span><br><span class="line">输出：</span><br><span class="line">SysExit</span><br><span class="line">outer</span><br></pre></td></tr></table></figure>
<h4 id="KeyboardIterrupt"><a href="#KeyboardIterrupt" class="headerlink" title="KeyboardIterrupt"></a>KeyboardIterrupt</h4><p>对应的捕获用户中断行为 <code>Ctrl + c</code></p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    <span class="keyword">import</span> time</span><br><span class="line">    <span class="keyword">while</span> <span class="keyword">True</span>:</span><br><span class="line">        time.sleep(<span class="number">0.5</span>)</span><br><span class="line">        <span class="keyword">pass</span></span><br><span class="line"><span class="keyword">except</span> KeyboardInterrupt:</span><br><span class="line">    print(<span class="string">'ctrl + c'</span>)</span><br><span class="line">print(<span class="string">'outer'</span>)</span><br><span class="line">输出：</span><br><span class="line">ctrl + c</span><br><span class="line">outer</span><br><span class="line"><span class="comment"># 在pycharm中执行后，点击停止运行就会有输出</span></span><br></pre></td></tr></table></figure>
<h3 id="Exception及子类"><a href="#Exception及子类" class="headerlink" title="Exception及子类"></a>Exception及子类</h3><p>Exception是所有内建的、非系统退出的异常的基类，自定义异常应该继承自它</p>
<h4 id="SyntaxError-语法错误"><a href="#SyntaxError-语法错误" class="headerlink" title="SyntaxError 语法错误"></a>SyntaxError 语法错误</h4><p>Python将这种错误也归到异常类下面的Exception下的子类，但是这种错误是不可捕获的</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">def</span> <span class="title">a</span><span class="params">()</span>:</span></span><br><span class="line">    <span class="keyword">try</span>:</span><br><span class="line">        <span class="number">0</span>a = <span class="number">5</span></span><br><span class="line">    <span class="keyword">except</span>:</span><br><span class="line">        <span class="keyword">pass</span></span><br><span class="line">    </span><br><span class="line"><span class="comment"># 错误</span></span><br><span class="line"> File <span class="string">"test2.py"</span>, line <span class="number">3</span></span><br><span class="line">    <span class="number">0</span>a = <span class="number">5</span></span><br><span class="line">     ^</span><br><span class="line">SyntaxError: invalid syntax</span><br></pre></td></tr></table></figure>
<h4 id="ArithmeticError"><a href="#ArithmeticError" class="headerlink" title="ArithmeticError"></a>ArithmeticError</h4><p>所有算术计算引发的异常，其子类有除零异常等</p>
<h4 id="LookupError"><a href="#LookupError" class="headerlink" title="LookupError"></a>LookupError</h4><p>使用映射的键或序列的索引无效时引发的异常的基类：<code>IndexError</code>, <code>KeyError</code></p>
<h4 id="自定义异常"><a href="#自定义异常" class="headerlink" title="自定义异常"></a>自定义异常</h4><p>从Exception继承的类</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br></pre></td><td class="code"><pre><span class="line"><span class="class"><span class="keyword">class</span> <span class="title">MyException</span><span class="params">(Exception)</span>:</span></span><br><span class="line">    <span class="keyword">pass</span></span><br><span class="line"></span><br><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    <span class="keyword">raise</span> MyException()</span><br><span class="line"><span class="keyword">except</span> MyException:  <span class="comment"># 捕获自定义异常</span></span><br><span class="line">    print(<span class="string">'catch the exception'</span>)</span><br><span class="line">输出：</span><br><span class="line">catch the exception</span><br></pre></td></tr></table></figure>
<h3 id="异常的捕获-1"><a href="#异常的捕获-1" class="headerlink" title="异常的捕获"></a>异常的捕获</h3><p>except 可以捕获多个异常</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br></pre></td><td class="code"><pre><span class="line"><span class="class"><span class="keyword">class</span> <span class="title">MyException</span><span class="params">(Exception)</span>:</span></span><br><span class="line">    <span class="keyword">pass</span></span><br><span class="line"></span><br><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    a = <span class="number">1</span>/<span class="number">0</span> </span><br><span class="line">    <span class="keyword">raise</span> MyException()  <span class="comment"># 自定义</span></span><br><span class="line">    open(<span class="string">'a1.txt'</span>)</span><br><span class="line"><span class="keyword">except</span> MyException:</span><br><span class="line">    print(<span class="string">'catch the MyException'</span>)</span><br><span class="line"><span class="keyword">except</span> ZeroDivisionError:</span><br><span class="line">    print(<span class="string">'1/0'</span>)</span><br><span class="line"><span class="keyword">except</span> Exception: <span class="comment"># 调整except的顺序</span></span><br><span class="line">    print(<span class="string">'Exception  # 只有'</span>)</span><br><span class="line">输出：</span><br><span class="line"><span class="number">1</span>/<span class="number">0</span>  <span class="comment"># 只有a = 1/0时的输出</span></span><br><span class="line">catch the MyException  <span class="comment"># 只有raise MyException()时的输出</span></span><br><span class="line">Exception  <span class="comment"># 只有open('a1.txt')时的输出</span></span><br></pre></td></tr></table></figure>
<p>捕获规则</p>
<p>捕获是从上到下依次比较，如果匹配，则执行匹配的except语句块</p>
<p>如果被一个except语句捕获，其他except语句就不会再次捕获了</p>
<p>如果没有任何一个except语句捕获到这个异常，则该异常向外抛出</p>
<p>捕获的原则</p>
<p>从小到大，从具体到宽泛</p>
<h3 id="as子句"><a href="#as子句" class="headerlink" title="as子句"></a>as子句</h3><p>被抛出的异常，应该是异常的实例，如何获得这个对象呢？使用as子句</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br></pre></td><td class="code"><pre><span class="line"><span class="class"><span class="keyword">class</span> <span class="title">MyException</span><span class="params">(Exception)</span>:</span></span><br><span class="line">    <span class="function"><span class="keyword">def</span> <span class="title">__init__</span><span class="params">(self, code, message)</span>:</span></span><br><span class="line">        self.code = code</span><br><span class="line">        self.message = message</span><br><span class="line">        </span><br><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    <span class="keyword">raise</span> MyException  <span class="comment"># 抛出MyException自定义异常</span></span><br><span class="line"><span class="keyword">except</span> MyException <span class="keyword">as</span> e:</span><br><span class="line">    print(<span class="string">'MyException = &#123;&#125; &#123;&#125;'</span>.format(e.code, e.message))</span><br><span class="line"><span class="keyword">except</span> Exception <span class="keyword">as</span> e:</span><br><span class="line">    print(<span class="string">'Exception = &#123;&#125;'</span>.format(e))</span><br><span class="line">    </span><br><span class="line"><span class="comment"># 运行结果：</span></span><br><span class="line">Exception = __init__() missing <span class="number">2</span> required positional arguments: <span class="string">'code'</span> <span class="keyword">and</span> <span class="string">'message'</span></span><br></pre></td></tr></table></figure>
<p>raise 后跟类名是无参构造实例，因此需要2个参数</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br></pre></td><td class="code"><pre><span class="line"><span class="class"><span class="keyword">class</span> <span class="title">MyException</span><span class="params">(Exception)</span>:</span></span><br><span class="line">    <span class="function"><span class="keyword">def</span> <span class="title">__init__</span><span class="params">(self, code, message)</span>:</span></span><br><span class="line">        self.code = code</span><br><span class="line">        self.message = message</span><br><span class="line">        </span><br><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    <span class="keyword">raise</span> MyException(<span class="number">200</span>, <span class="string">'ok'</span>)</span><br><span class="line"><span class="keyword">except</span> MyException <span class="keyword">as</span> e:</span><br><span class="line">    print(<span class="string">'MyException = &#123;&#125; &#123;&#125;'</span>.format(e.code, e.message))</span><br><span class="line"><span class="keyword">except</span> Exception <span class="keyword">as</span> e:</span><br><span class="line">    print(<span class="string">'Exception = &#123;&#125;'</span>.format(e))</span><br><span class="line">输出：</span><br><span class="line">Myexception = <span class="number">200</span> ok</span><br></pre></td></tr></table></figure>
<h3 id="finally子句"><a href="#finally子句" class="headerlink" title="finally子句"></a>finally子句</h3><p>finally：最终，即最后一定要执行的。<code>try ... finally</code>语句块中，不管是否发生了异常，都要执行finally的部分</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    f = open(<span class="string">'test.txt'</span>)</span><br><span class="line"><span class="keyword">except</span> FileNotFoundError <span class="keyword">as</span> e:</span><br><span class="line">    print(<span class="string">'&#123;&#125; &#123;&#125; &#123;&#125;'</span>.format(e.__class__, e.errno, e.strerror))</span><br><span class="line"><span class="keyword">finally</span>:</span><br><span class="line">    print(<span class="string">'清理工作'</span>)</span><br><span class="line">    f.close()</span><br><span class="line">输出：</span><br><span class="line">Traceback (most recent call last):</span><br><span class="line">  File <span class="string">"/home/shouyu/PycharmProjects/test/练习/异常处理/课上练习.py"</span>, line <span class="number">119</span>, <span class="keyword">in</span> &lt;module&gt;</span><br><span class="line">    f = open(<span class="string">'test.txt'</span>)</span><br><span class="line">FileNotFoundError: [Errno <span class="number">2</span>] No such file <span class="keyword">or</span> directory: <span class="string">'test.txt'</span></span><br><span class="line"></span><br><span class="line">During handling of the above exception, another exception occurred:</span><br><span class="line"></span><br><span class="line">Traceback (most recent call last):</span><br><span class="line">  File <span class="string">"/home/shouyu/PycharmProjects/test/练习/异常处理/课上练习.py"</span>, line <span class="number">124</span>, <span class="keyword">in</span> &lt;module&gt;</span><br><span class="line">    f.close()</span><br><span class="line">NameError: name <span class="string">'f'</span> <span class="keyword">is</span> <span class="keyword">not</span> defined</span><br><span class="line">清理工作</span><br></pre></td></tr></table></figure>
<p>注意上例中的<code>f</code>的作用域，解决的办法是外部定义<code>f</code></p>
<p>finally中一般放置资源的清理、释放工作的语句</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br></pre></td><td class="code"><pre><span class="line">f = <span class="keyword">None</span></span><br><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    f = open(<span class="string">'test.txt'</span>)</span><br><span class="line"><span class="keyword">except</span> Exception <span class="keyword">as</span> e:</span><br><span class="line">    print(<span class="string">'&#123;&#125;'</span>.format(e))</span><br><span class="line"><span class="keyword">finally</span>:</span><br><span class="line">    print(<span class="string">'清理工作'</span>)</span><br><span class="line">    <span class="keyword">if</span> f:</span><br><span class="line">        f.close()</span><br><span class="line">输出：</span><br><span class="line">[Errno <span class="number">2</span>] No such file <span class="keyword">or</span> directory: <span class="string">'test.txt'</span></span><br><span class="line">清理工作</span><br></pre></td></tr></table></figure>
<p>也可以在finally中再次捕捉异常</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    f = open(<span class="string">'test.txt'</span>)</span><br><span class="line"><span class="keyword">except</span> Exception <span class="keyword">as</span> e:</span><br><span class="line">    print(<span class="string">'&#123;&#125;'</span>.format(e))</span><br><span class="line"><span class="keyword">finally</span>:</span><br><span class="line">    print(<span class="string">'清理工作'</span>)</span><br><span class="line">    <span class="keyword">try</span>:</span><br><span class="line">        f.close()</span><br><span class="line">    <span class="keyword">except</span> NameError <span class="keyword">as</span> e:</span><br><span class="line">        print(e)</span><br><span class="line">输出：</span><br><span class="line">[Errno <span class="number">2</span>] No such file <span class="keyword">or</span> directory: <span class="string">'test.txt'</span></span><br><span class="line">清理工作</span><br><span class="line">name <span class="string">'f'</span> <span class="keyword">is</span> <span class="keyword">not</span> defined</span><br></pre></td></tr></table></figure>
<h4 id="finally-执行时机"><a href="#finally-执行时机" class="headerlink" title="finally 执行时机"></a>finally 执行时机</h4><figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br></pre></td><td class="code"><pre><span class="line"><span class="comment"># 测试1</span></span><br><span class="line"><span class="function"><span class="keyword">def</span> <span class="title">foo</span><span class="params">()</span>:</span></span><br><span class="line">    <span class="keyword">try</span>:</span><br><span class="line">        <span class="keyword">return</span> <span class="number">3</span></span><br><span class="line">    <span class="keyword">finally</span>:</span><br><span class="line">        print(<span class="string">'finally'</span>)</span><br><span class="line">    print(<span class="string">'=='</span>)</span><br><span class="line">print(foo())</span><br><span class="line"><span class="comment"># 进入try，执行return 3，虽然函数要返回，但是finally一定还要执行，所以打印了finally后，函数返回</span></span><br><span class="line">输出：</span><br><span class="line"><span class="keyword">finally</span></span><br><span class="line"><span class="number">3</span></span><br><span class="line"></span><br><span class="line"><span class="comment"># 测试2</span></span><br><span class="line"><span class="function"><span class="keyword">def</span> <span class="title">foo</span><span class="params">()</span>:</span></span><br><span class="line">    <span class="comment"># return 1  # 这里加入return，就不会向下执行了，也就和try...finally无关了</span></span><br><span class="line">    <span class="keyword">try</span>:</span><br><span class="line">        <span class="keyword">return</span> <span class="number">3</span></span><br><span class="line">    <span class="keyword">finally</span>:</span><br><span class="line">        <span class="keyword">return</span> <span class="number">5</span></span><br><span class="line">    print(<span class="string">'=='</span>)</span><br><span class="line">print(foo())</span><br><span class="line"><span class="comment"># 进入try，执行return 3，虽然函数要返回，但是finally一定还要执行，所以执行return 5，函数返回。5被放在栈</span></span><br><span class="line"><span class="comment"># 顶，所以返回5。简单说，函数的返回值取决于最后一个执行的return语句，而finally则是fry ... finally中最后</span></span><br><span class="line"><span class="comment"># 执行的语句块</span></span><br><span class="line">输出：</span><br><span class="line"><span class="number">5</span></span><br></pre></td></tr></table></figure>
<h3 id="异常的传递"><a href="#异常的传递" class="headerlink" title="异常的传递"></a>异常的传递</h3><figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">def</span> <span class="title">foo1</span><span class="params">()</span>:</span></span><br><span class="line">    <span class="keyword">return</span> <span class="number">1</span>/<span class="number">0</span></span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">def</span> <span class="title">foo2</span><span class="params">()</span>:</span></span><br><span class="line">    print(<span class="string">'foo2 start'</span>)</span><br><span class="line">    foo1()</span><br><span class="line">    print(<span class="string">'foo2 stop'</span>)</span><br><span class="line">foo2()</span><br><span class="line">输出：</span><br><span class="line">foo2 start</span><br><span class="line">Traceback (most recent call last):</span><br><span class="line">  File <span class="string">"/home/shouyu/PycharmProjects/test/练习/异常处理/课上练习.py"</span>, line <span class="number">172</span>, <span class="keyword">in</span> &lt;module&gt;</span><br><span class="line">    foo2()</span><br><span class="line">  File <span class="string">"/home/shouyu/PycharmProjects/test/练习/异常处理/课上练习.py"</span>, line <span class="number">170</span>, <span class="keyword">in</span> foo2</span><br><span class="line">    foo1()</span><br><span class="line">  File <span class="string">"/home/shouyu/PycharmProjects/test/练习/异常处理/课上练习.py"</span>, line <span class="number">166</span>, <span class="keyword">in</span> foo1</span><br><span class="line">    <span class="keyword">return</span> <span class="number">1</span>/<span class="number">0</span></span><br><span class="line">ZeroDivisionError: division by zero</span><br></pre></td></tr></table></figure>
<p>foo2调用了foo1，foo1产生的异常，传递到了foo2中。</p>
<p>异常总是向外层抛出，如果外层没有处理这个异常，就会继续向外抛出</p>
<p>如果内层捕获并处理了异常，外部就不能捕获到了</p>
<p>如果到了最外层还是没有被处理，就会中断异常所在的线程的执行</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br><span class="line">35</span><br><span class="line">36</span><br><span class="line">37</span><br><span class="line">38</span><br><span class="line">39</span><br><span class="line">40</span><br><span class="line">41</span><br><span class="line">42</span><br><span class="line">43</span><br><span class="line">44</span><br><span class="line">45</span><br><span class="line">46</span><br><span class="line">47</span><br><span class="line">48</span><br><span class="line">49</span><br><span class="line">50</span><br><span class="line">51</span><br><span class="line">52</span><br></pre></td><td class="code"><pre><span class="line"><span class="comment"># 线程中测试异常</span></span><br><span class="line"><span class="keyword">import</span> threading</span><br><span class="line"><span class="keyword">import</span> time</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">def</span> <span class="title">foo1</span><span class="params">()</span>:</span></span><br><span class="line">    <span class="keyword">return</span> <span class="number">1</span>/<span class="number">0</span></span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">def</span> <span class="title">foo2</span><span class="params">()</span>:</span></span><br><span class="line">    time.sleep(<span class="number">3</span>)  <span class="comment"># 3秒后抛出异常</span></span><br><span class="line">    print(<span class="string">'foo2 start'</span>)</span><br><span class="line">    foo1()</span><br><span class="line">    print(<span class="string">'foo2 stop'</span>)</span><br><span class="line">    </span><br><span class="line">t = threading.Thread(target=foo2)</span><br><span class="line">t.start()</span><br><span class="line"></span><br><span class="line"><span class="keyword">while</span> <span class="keyword">True</span>:</span><br><span class="line">    time.sleep(<span class="number">1</span>)</span><br><span class="line">    print(<span class="string">'Everything OK'</span>)</span><br><span class="line">    <span class="keyword">if</span> t.is_alive():</span><br><span class="line">        print(<span class="string">'alive'</span>)</span><br><span class="line">    <span class="keyword">else</span>:</span><br><span class="line">        print(<span class="string">'dead'</span>)</span><br><span class="line">输出：</span><br><span class="line">Everything ok</span><br><span class="line">alive</span><br><span class="line">Everything ok</span><br><span class="line">alive</span><br><span class="line">Everything ok</span><br><span class="line">alive</span><br><span class="line">foo2 start</span><br><span class="line">Exception <span class="keyword">in</span> thread Thread<span class="number">-1</span>:</span><br><span class="line">Traceback (most recent call last):</span><br><span class="line">  File <span class="string">"/home/shouyu/anaconda3/lib/python3.7/threading.py"</span>, line <span class="number">917</span>, <span class="keyword">in</span> _bootstrap_inner</span><br><span class="line">    self.run()</span><br><span class="line">  File <span class="string">"/home/shouyu/anaconda3/lib/python3.7/threading.py"</span>, line <span class="number">865</span>, <span class="keyword">in</span> run</span><br><span class="line">    self._target(*self._args, **self._kwargs)</span><br><span class="line">  File <span class="string">"/home/shouyu/PycharmProjects/test/练习/异常处理/课上练习.py"</span>, line <span class="number">183</span>, <span class="keyword">in</span> foo2</span><br><span class="line">    foo1()</span><br><span class="line">  File <span class="string">"/home/shouyu/PycharmProjects/test/练习/异常处理/课上练习.py"</span>, line <span class="number">178</span>, <span class="keyword">in</span> foo1</span><br><span class="line">    <span class="keyword">return</span> <span class="number">1</span>/<span class="number">0</span></span><br><span class="line">ZeroDivisionError: division by zero</span><br><span class="line">    </span><br><span class="line">Everything ok</span><br><span class="line">dead    <span class="comment"># 这表示线程被中断了吗？</span></span><br><span class="line">Everything ok</span><br><span class="line">dead</span><br><span class="line">Everything ok</span><br><span class="line">dead</span><br><span class="line">Everything ok</span><br><span class="line">dead</span><br><span class="line"><span class="meta">... </span>...</span><br></pre></td></tr></table></figure>
<h3 id="try嵌套"><a href="#try嵌套" class="headerlink" title="try嵌套"></a>try嵌套</h3><figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    <span class="keyword">try</span>:</span><br><span class="line">        ret = <span class="number">1</span> / <span class="number">0</span></span><br><span class="line">    <span class="keyword">except</span> KeyError <span class="keyword">as</span> e:</span><br><span class="line">        print(e)</span><br><span class="line">    <span class="keyword">else</span>:</span><br><span class="line">        print(<span class="string">'inner OK'</span>)</span><br><span class="line">    <span class="keyword">finally</span>:</span><br><span class="line">        print(<span class="string">'inner fin'</span>)</span><br><span class="line"><span class="keyword">except</span>:</span><br><span class="line">    print(<span class="string">'outer catch'</span>)</span><br><span class="line"><span class="keyword">finally</span>:</span><br><span class="line">    print(<span class="string">'outer fin'</span>)</span><br><span class="line">输出：</span><br><span class="line">inner fin</span><br><span class="line">outer catch</span><br><span class="line">outer fin</span><br></pre></td></tr></table></figure>
<p>内部捕获不到异常，会向外层传递异常</p>
<p><strong>但是如果内层有finally且其中有return、break语句，则异常就不会继续向外抛出</strong></p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">def</span> <span class="title">foo</span><span class="params">()</span>:</span></span><br><span class="line">    <span class="keyword">try</span>:</span><br><span class="line">        ret = <span class="number">1</span> / <span class="number">0</span></span><br><span class="line">    <span class="keyword">except</span> KeyError <span class="keyword">as</span> e:</span><br><span class="line">        print(e)</span><br><span class="line">    <span class="keyword">finally</span>:</span><br><span class="line">        print(<span class="string">'inner fin'</span>)</span><br><span class="line">        <span class="keyword">return</span> <span class="comment"># 异常被丢弃</span></span><br><span class="line">    </span><br><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    foo()</span><br><span class="line"><span class="keyword">except</span>:</span><br><span class="line">    print(<span class="string">'outer catch'</span>)</span><br><span class="line"><span class="keyword">finally</span>:</span><br><span class="line">    print(<span class="string">'outer fin'</span>)</span><br><span class="line">输出：</span><br><span class="line">inner fin</span><br><span class="line">outer fin</span><br></pre></td></tr></table></figure>
<h3 id="异常的捕获时机"><a href="#异常的捕获时机" class="headerlink" title="异常的捕获时机"></a>异常的捕获时机</h3><ol>
<li>立即捕获</li>
</ol>
<p>需要立即返回一个明确的结果</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">def</span> <span class="title">parse_int</span><span class="params">(s)</span>:</span></span><br><span class="line">    <span class="keyword">try</span>:</span><br><span class="line">        <span class="keyword">return</span> int(s)</span><br><span class="line">    <span class="keyword">except</span>:</span><br><span class="line">        <span class="keyword">return</span> <span class="number">0</span></span><br><span class="line">print(parse_int(<span class="string">'s'</span>))</span><br><span class="line">输出：</span><br><span class="line"><span class="number">0</span></span><br></pre></td></tr></table></figure>
<ol start="2">
<li>边界捕获</li>
</ol>
<p>封装产生了边界。</p>
<p>例如，写了一个模块，用户调用这个模块的时候捕获异常，模块内部不需要捕获、处理异常，一旦内部处理了，外部调用者就无法感知了。</p>
<p>例如，open函数，出现的异常交给调用者处理，文件存在了，就不用再创建了，看是否修改还是删除</p>
<p>例如，自己写了一个类，使用open函数，但是出现了异常不知道如何处理，就继续向外层抛出，一般来说最外层也是边界，必须处理这个异常了，否则线程退出</p>
<h3 id="else子句"><a href="#else子句" class="headerlink" title="else子句"></a>else子句</h3><figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    ret = <span class="number">1</span> * <span class="number">0</span></span><br><span class="line"><span class="keyword">except</span> ArithmeticError <span class="keyword">as</span> e:</span><br><span class="line">    print(e)</span><br><span class="line"><span class="keyword">else</span>:</span><br><span class="line">    print(<span class="string">'OK'</span>)</span><br><span class="line"><span class="keyword">finally</span>:</span><br><span class="line">    print(<span class="string">'fin'</span>)</span><br><span class="line">输出：</span><br><span class="line">ok</span><br><span class="line">fin</span><br></pre></td></tr></table></figure>
<p>else子句</p>
<p><strong>没有任何异常发生</strong>，则执行</p>
<h3 id="总结"><a href="#总结" class="headerlink" title="总结"></a>总结</h3><figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    &lt;语句&gt;   <span class="comment"># 运行别的代码</span></span><br><span class="line"><span class="keyword">except</span> &lt;异常类&gt;:</span><br><span class="line">    &lt;语句&gt;  <span class="comment"># 捕获某种类型的异常</span></span><br><span class="line"><span class="keyword">except</span> &lt;异常类&gt; <span class="keyword">as</span> &lt;变量名&gt;:</span><br><span class="line">    &lt;语句&gt;   <span class="comment"># 捕获某种类型的异常并获得对象</span></span><br><span class="line"><span class="keyword">else</span>:</span><br><span class="line">    &lt;语句&gt;   <span class="comment"># 如果没有异常发生就执行</span></span><br><span class="line"><span class="keyword">finally</span>:</span><br><span class="line">    &lt;语句&gt;   <span class="comment"># 退出try时总会执行</span></span><br></pre></td></tr></table></figure>
<p><strong>try的工作原理</strong></p>
<ol>
<li>如果try中语句执行时发生异常，搜索except子句，并执行第一个匹配该异常的except子句</li>
<li>如果try中语句执行时发生异常，却没有匹配的except子句，异常将被递交到外层的try，如果外层不处理这个异常，异常将继续向外层传递。如果都不处理该异常，则会传递到最外层，如果还没有处理，就终止异常所在的线程</li>
<li>如果在try执行时没有发生异常，将执行else子句中的语句</li>
<li>无论try中是否发生异常，finally子句最终都会执行</li>
</ol>
<h3 id="笔记"><a href="#笔记" class="headerlink" title="笔记"></a>笔记</h3><p>异常与错误是有区别的，错误一般是逻辑或语法有错误，这不属于意外。代码没有问题，但是出现了意外 ，如网络无法连接或文件不存在，这属于异常，异常是避免不了的。一个健壮的程序，尽可能的避免错误，尽可能的捕获、处理各种异常。简单的代码逻辑错误会少一些</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br><span class="line">35</span><br><span class="line">36</span><br><span class="line">37</span><br><span class="line">38</span><br><span class="line">39</span><br><span class="line">40</span><br><span class="line">41</span><br><span class="line">42</span><br><span class="line">43</span><br><span class="line">44</span><br><span class="line">45</span><br><span class="line">46</span><br><span class="line">47</span><br><span class="line">48</span><br><span class="line">49</span><br><span class="line">50</span><br><span class="line">51</span><br><span class="line">52</span><br><span class="line">53</span><br><span class="line">54</span><br><span class="line">55</span><br><span class="line">56</span><br><span class="line">57</span><br><span class="line">58</span><br><span class="line">59</span><br><span class="line">60</span><br><span class="line">61</span><br><span class="line">62</span><br><span class="line">63</span><br><span class="line">64</span><br><span class="line">65</span><br><span class="line">66</span><br><span class="line">67</span><br><span class="line">68</span><br><span class="line">69</span><br><span class="line">70</span><br><span class="line">71</span><br><span class="line">72</span><br><span class="line">73</span><br><span class="line">74</span><br><span class="line">75</span><br><span class="line">76</span><br><span class="line">77</span><br><span class="line">78</span><br><span class="line">79</span><br><span class="line">80</span><br><span class="line">81</span><br><span class="line">82</span><br><span class="line">83</span><br><span class="line">84</span><br><span class="line">85</span><br><span class="line">86</span><br><span class="line">87</span><br><span class="line">88</span><br><span class="line">89</span><br><span class="line">90</span><br><span class="line">91</span><br><span class="line">92</span><br><span class="line">93</span><br><span class="line">94</span><br><span class="line">95</span><br><span class="line">96</span><br><span class="line">97</span><br><span class="line">98</span><br><span class="line">99</span><br><span class="line">100</span><br><span class="line">101</span><br><span class="line">102</span><br><span class="line">103</span><br><span class="line">104</span><br><span class="line">105</span><br><span class="line">106</span><br><span class="line">107</span><br><span class="line">108</span><br><span class="line">109</span><br><span class="line">110</span><br><span class="line">111</span><br><span class="line">112</span><br><span class="line">113</span><br><span class="line">114</span><br><span class="line">115</span><br><span class="line">116</span><br><span class="line">117</span><br><span class="line">118</span><br><span class="line">119</span><br><span class="line">120</span><br><span class="line">121</span><br><span class="line">122</span><br><span class="line">123</span><br><span class="line">124</span><br><span class="line">125</span><br><span class="line">126</span><br><span class="line">127</span><br><span class="line">128</span><br><span class="line">129</span><br><span class="line">130</span><br><span class="line">131</span><br><span class="line">132</span><br><span class="line">133</span><br><span class="line">134</span><br><span class="line">135</span><br><span class="line">136</span><br><span class="line">137</span><br><span class="line">138</span><br><span class="line">139</span><br><span class="line">140</span><br><span class="line">141</span><br><span class="line">142</span><br><span class="line">143</span><br><span class="line">144</span><br><span class="line">145</span><br><span class="line">146</span><br><span class="line">147</span><br></pre></td><td class="code"><pre><span class="line">语法：</span><br><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    待捕获异常的代码块</span><br><span class="line"><span class="keyword">except</span> [异常类型]:</span><br><span class="line">    异常的处理代码块</span><br><span class="line">===========================================================================================</span><br><span class="line"><span class="keyword">with</span> open(<span class="string">'test'</span>) <span class="keyword">as</span> f:   <span class="comment"># 这属于异常，异常报错是有Traceback字样的，这是一个栈的概念</span></span><br><span class="line">    <span class="keyword">pass</span></span><br><span class="line">输出：</span><br><span class="line">Traceback (most recent call last):</span><br><span class="line">  File <span class="string">"/home/shouyu/PycharmProjects/test/异常处理.py"</span>, line <span class="number">1</span>, <span class="keyword">in</span> &lt;module&gt;</span><br><span class="line">    <span class="keyword">with</span> open(<span class="string">'test'</span>) <span class="keyword">as</span> f:</span><br><span class="line">FileNotFoundError: [Errno <span class="number">2</span>] No such file <span class="keyword">or</span> directory: <span class="string">'test'</span></span><br><span class="line">===========================================================================================</span><br><span class="line"><span class="function"><span class="keyword">def</span> 0<span class="title">q</span><span class="params">()</span>:</span>  <span class="comment"># 这属于错误</span></span><br><span class="line">    <span class="keyword">pass</span></span><br><span class="line">输出：</span><br><span class="line">  File <span class="string">"/home/shouyu/PycharmProjects/test/异常处理.py"</span>, line <span class="number">3</span></span><br><span class="line">    <span class="function"><span class="keyword">def</span> 0<span class="title">a</span><span class="params">()</span>:</span></span><br><span class="line">        ^</span><br><span class="line">SyntaxError: invalid syntax</span><br><span class="line">===========================================================================================</span><br><span class="line"><span class="keyword">try</span>:  </span><br><span class="line"><span class="comment"># 尝试观察下面的语句，如果发现下面的某一条语句在执行的过程中产生了一个异常，就会把它抓住并交给except语句处理</span></span><br><span class="line">    f = open(<span class="string">'test'</span>)</span><br><span class="line">    print(<span class="string">'after'</span>)</span><br><span class="line"><span class="keyword">except</span>:</span><br><span class="line">    print(<span class="string">'exception'</span>)</span><br><span class="line">输出：</span><br><span class="line">exception</span><br><span class="line">===========================================================================================</span><br><span class="line"><span class="keyword">try</span>:  </span><br><span class="line">    f = open(<span class="string">'test'</span>, <span class="string">'w'</span>)  <span class="comment"># 如果没有test文件就创建，这样就不会有异常了</span></span><br><span class="line">    print(<span class="string">'after'</span>)</span><br><span class="line"><span class="keyword">except</span>:  <span class="comment"># 这是捕获异常的，没有异常就不会执行下面的语句</span></span><br><span class="line">    print(<span class="string">'exception'</span>)</span><br><span class="line">输出：</span><br><span class="line">after</span><br><span class="line">===========================================================================================</span><br><span class="line"><span class="keyword">try</span>:  </span><br><span class="line">    f = open(<span class="string">'test'</span>, <span class="string">'w'</span>)  <span class="comment"># 如果没有test文件就创建，这样就不会有异常了</span></span><br><span class="line">    print(<span class="string">'after'</span>)</span><br><span class="line">    <span class="number">0</span>a = <span class="number">6</span>  <span class="comment"># 这不会捕获到异常，只会检查出语法错误</span></span><br><span class="line"><span class="keyword">except</span>:  <span class="comment"># 这是捕获所有异常的，没有异常就不会执行下面的语句</span></span><br><span class="line">    print(<span class="string">'exception'</span>)</span><br><span class="line">输出：</span><br><span class="line">  File <span class="string">"/home/shouyu/PycharmProjects/test/异常处理.py"</span>, line <span class="number">8</span></span><br><span class="line">    <span class="number">0</span>a = <span class="number">6</span></span><br><span class="line">     ^</span><br><span class="line">SyntaxError: invalid syntax</span><br><span class="line">    ===========================================================================================</span><br><span class="line"><span class="keyword">try</span>:  </span><br><span class="line">    f = open(<span class="string">'test1'</span>, <span class="string">'r'</span>)  <span class="comment"># 如果没有test文件就创建，这样就不会有异常了</span></span><br><span class="line">    print(<span class="string">'after'</span>)</span><br><span class="line">    <span class="comment"># a = 1 + 3   # 如果希望写成1 + 2，但写成了1 + 3，这种属于逻辑错误，这是捕获不到的</span></span><br><span class="line"><span class="keyword">except</span>:  <span class="comment"># 这是捕获异常的，没有异常就不会执行下面的语句</span></span><br><span class="line">    print(<span class="string">'exception'</span>)  <span class="comment"># 执行到这里，打印完就中断了，不会再执行try中的print了</span></span><br><span class="line">    </span><br><span class="line">print(<span class="string">'outer'</span>)</span><br><span class="line">输出：</span><br><span class="line">exception</span><br><span class="line">outer</span><br><span class="line">===========================================================================================</span><br><span class="line"><span class="comment"># 除零异常</span></span><br><span class="line"><span class="function"><span class="keyword">def</span> <span class="title">foo</span><span class="params">()</span>:</span></span><br><span class="line">    print(<span class="string">'before'</span>)</span><br><span class="line">    <span class="function"><span class="keyword">def</span> <span class="title">bar</span><span class="params">()</span>:</span></span><br><span class="line">        print(<span class="number">1</span>/<span class="number">0</span>) <span class="comment"># 除零异常。这是在运行期由解释器抛出异常</span></span><br><span class="line"></span><br><span class="line">    bar()  <span class="comment"># 一调用就会出问题，下面就不会打印了</span></span><br><span class="line">    print(<span class="string">'after'</span>)</span><br><span class="line">foo()</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">def</span> <span class="title">bar</span><span class="params">()</span>:</span>  <span class="comment"># 这个bar函数与上面的bar函数没有关系，因为作用域不一样</span></span><br><span class="line">    print(<span class="string">'before'</span>)</span><br><span class="line">    <span class="keyword">raise</span> Exception(<span class="string">'my exception'</span>)  </span><br><span class="line"><span class="comment"># 这是人为向外抛出异常，抛出的Exception()可能是函数也可能是类。Exception实际是类，这是调用类的new和</span></span><br><span class="line"><span class="comment"># __init__方法，把类的对象构造出来。这是把代码丢给最外层的当前解释器，也就是运行它的环境，解释器发现有问题就</span></span><br><span class="line"><span class="comment"># 会抛出异常，解释器不知道你要干什么，需要你自己处理。解释器只是替你拿到了，你需要用try来处理</span></span><br><span class="line"><span class="comment"># 异常是一种机制，在出问题时使用这种机制修正这个问题</span></span><br><span class="line"><span class="comment"># raise语句后面什么都没有，表示抛出最近一个被激活的异常，如果没有被激活的异常，则抛出类型异常。这种方法很少用，一般会加上一个对象，如raise Exception('my exception') 。激活异常指刚才正在发生的异常，这种方法很少用。用raise一般抛出自己定义的异常。raise后应该是BaseException类（这是一个基类，是所有异常的祖先类）的子类或实例，如果是类，如raise Exception，将被无参实例化。</span></span><br><span class="line">    print(<span class="string">'after'</span>)</span><br><span class="line">bar()</span><br><span class="line">输出：</span><br><span class="line">Traceback (most recent call last):</span><br><span class="line">  File <span class="string">"/home/shouyu/PycharmProjects/test/异常处理.py"</span>, line <span class="number">27</span>, <span class="keyword">in</span> &lt;module&gt;</span><br><span class="line">    foo()</span><br><span class="line">  File <span class="string">"/home/shouyu/PycharmProjects/test/异常处理.py"</span>, line <span class="number">25</span>, <span class="keyword">in</span> foo</span><br><span class="line">    bar()</span><br><span class="line">  File <span class="string">"/home/shouyu/PycharmProjects/test/异常处理.py"</span>, line <span class="number">23</span>, <span class="keyword">in</span> bar</span><br><span class="line">    print(<span class="number">1</span>/<span class="number">0</span>)</span><br><span class="line">ZeroDivisionError: division by zero</span><br><span class="line">before</span><br><span class="line">===========================================================================================</span><br><span class="line"><span class="comment"># 激活异常测试</span></span><br><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    <span class="number">1</span>/<span class="number">0</span>  <span class="comment"># 执行到这里一定会抛异常</span></span><br><span class="line">    print(<span class="string">'1/0'</span>) <span class="comment"># 因为上面抛出了异常，所以这里不会打印</span></span><br><span class="line"><span class="keyword">except</span>:</span><br><span class="line">    <span class="keyword">try</span>:</span><br><span class="line">        <span class="keyword">raise</span>   <span class="comment"># 为了借用上面抛出的异常，所以这里用了raise，这不能写在try中，因为try中捕获到异常就会中断并转到except语句处理，所以写在try中也不会执行</span></span><br><span class="line">    <span class="keyword">except</span> Exception <span class="keyword">as</span> e:  <span class="comment"># 这里是期待一个Exception异常来并给e，最后打印出来</span></span><br><span class="line">        print(e)</span><br><span class="line">输出：</span><br><span class="line">division by zero</span><br><span class="line">===========================================================================================</span><br><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    <span class="number">1</span>/<span class="number">0</span></span><br><span class="line"><span class="keyword">except</span> Exception:  <span class="comment"># Exception是类，是BaseException的子类</span></span><br><span class="line">    print(<span class="string">'catch U'</span>)</span><br><span class="line">输出：</span><br><span class="line">catch U</span><br><span class="line">===========================================================================================</span><br><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    <span class="number">1</span>/<span class="number">0</span></span><br><span class="line"><span class="keyword">except</span> ArithmeticError:  <span class="comment"># Exception是类，是BaseException的子类</span></span><br><span class="line">    print(<span class="string">'catch U'</span>)</span><br><span class="line">输出：</span><br><span class="line">catch U</span><br><span class="line">===========================================================================================</span><br><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    <span class="number">1</span>/<span class="number">0</span></span><br><span class="line"><span class="keyword">except</span> KeyError:  <span class="comment"># 这里就捕获不到了，因为写的类型KeyError不对</span></span><br><span class="line">    print(<span class="string">'catch U'</span>)</span><br><span class="line">输出：</span><br><span class="line">Traceback (most recent call last):</span><br><span class="line">  File <span class="string">"/home/shouyu/PycharmProjects/test/异常处理.py"</span>, line <span class="number">43</span>, <span class="keyword">in</span> &lt;module&gt;</span><br><span class="line">    <span class="number">1</span>/<span class="number">0</span></span><br><span class="line">ZeroDivisionError: division by zero</span><br><span class="line">===========================================================================================</span><br><span class="line"><span class="keyword">import</span> sys</span><br><span class="line"></span><br><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    sys.exit()  <span class="comment"># 这里可以加入退出的状态码</span></span><br><span class="line"><span class="keyword">except</span> Exception: <span class="comment"># 这里可以不写，也可以写BaseException或SystemExit，都可以捕获异常。也就是要么什么都不写，或写调用的模块的父类或自己的类</span></span><br><span class="line">    print(<span class="string">'catch U'</span>)</span><br><span class="line">没有输出，因为sys不属于Exception的子类</span><br><span class="line">===========================================================================================</span><br><span class="line"><span class="keyword">import</span> sys</span><br><span class="line"><span class="keyword">import</span> time</span><br><span class="line"></span><br><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    <span class="keyword">while</span> <span class="keyword">True</span>:</span><br><span class="line">        time.sleep(<span class="number">1</span>)</span><br><span class="line">        print(<span class="string">'~~~~~~~~~~~~~~'</span>)</span><br><span class="line"><span class="keyword">except</span> KeyboardInterrupt:  <span class="comment"># 这要在脚本中使用ctrl + c才能捕获到</span></span><br><span class="line">    print(<span class="string">'catch U'</span>)</span><br></pre></td></tr></table></figure>
<p>Exception及子类</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br><span class="line">35</span><br><span class="line">36</span><br><span class="line">37</span><br><span class="line">38</span><br><span class="line">39</span><br><span class="line">40</span><br></pre></td><td class="code"><pre><span class="line">所有内建的，非系统退出的异常的基类，自定义异常应该继承自它</span><br><span class="line">自定义异常</span><br><span class="line"><span class="keyword">import</span> sys</span><br><span class="line"><span class="keyword">import</span> time</span><br><span class="line"></span><br><span class="line"><span class="class"><span class="keyword">class</span> <span class="title">MyException</span><span class="params">(Exception)</span>:</span></span><br><span class="line">    <span class="keyword">pass</span></span><br><span class="line"></span><br><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    <span class="keyword">raise</span> MyException() </span><br><span class="line"><span class="keyword">except</span> Exception:  <span class="comment"># 这里也可以用MyException，现在用了它的父类Exception</span></span><br><span class="line">    print(MyException.mro())</span><br><span class="line">输出：</span><br><span class="line">[&lt;class '__main__.MyException'&gt;, &lt;class 'Exception'&gt;, &lt;class 'BaseException'&gt;, &lt;class 'object'&gt;]</span><br><span class="line">===========================================================================================</span><br><span class="line">异常可以捕获多个</span><br><span class="line"><span class="keyword">import</span> sys</span><br><span class="line"><span class="keyword">import</span> time</span><br><span class="line"></span><br><span class="line"><span class="class"><span class="keyword">class</span> <span class="title">MyException</span><span class="params">(Exception)</span>:</span></span><br><span class="line">    <span class="function"><span class="keyword">def</span> <span class="title">__init__</span><span class="params">(self, xdata)</span>:</span></span><br><span class="line">        self.xdata = xdata</span><br><span class="line"></span><br><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    <span class="number">1</span>/<span class="number">0</span></span><br><span class="line">    open(<span class="string">'test'</span>, <span class="string">'w'</span>)</span><br><span class="line">    <span class="keyword">raise</span> MyException(<span class="string">"My Error"</span>)  <span class="comment"># 这里会抛异常，之后会在下面从上向下找匹配的except中的异常。传参是因为MyException继承自Exception，所以不会报错。这样下面调用MyException时就可以打印出这里的内容了，所以这里最好写清楚</span></span><br><span class="line">    <span class="comment"># raise MyException  # 这样只写类名，相当于无参构造，也就是无参实例化了。这里会产生空字符串，下面调用时打印的也是空字符串。如果上面写入一个初始化方法，加一个参数，就会报错了，提示少一个参数。如果没加参数就不会有这种问题，这种错误会被下面的except Exception捕获到，这个异常属于Exception的子类</span></span><br><span class="line">    </span><br><span class="line"><span class="keyword">except</span> MyException <span class="keyword">as</span> e: </span><br><span class="line"><span class="comment"># 这里就匹配到抛出的异常，这就会执行这里的print语句，之后就不会再执行下面的except语句了，这就像if...else语句一样，直接执行所有except外面的语句。这里就是抛出异常后从上向下查找except语句，匹配到哪个异常就执行哪个except下面的语句，之后跳出所有except语句，执行except外的语句。一次只会产生一个异常并处理。捕获异常最好把范围从小到大写</span></span><br><span class="line">    print(e)  <span class="comment"># 这相当于在调用MyException的__str__魔术方法，因为print方法默认调用__str__</span></span><br><span class="line"><span class="keyword">except</span> Exception <span class="keyword">as</span> e:  <span class="comment"># 这里的e和上面的e不会冲突，因为如果上面捕获了异常就退出了</span></span><br><span class="line">    print(e, type(e))  <span class="comment"># 拿到后可以打开出异常是什么，还可以打印出异常的类型</span></span><br><span class="line"><span class="keyword">except</span> InterruptedError:</span><br><span class="line">    print(<span class="string">'InterruptedError'</span>)</span><br><span class="line"><span class="keyword">except</span>:  <span class="comment"># 这个要加在最后，都匹配不到时就用这条捕获异常。或者用except Exception:也可以。</span></span><br><span class="line">    print()</span><br><span class="line">    </span><br><span class="line">print(<span class="string">'outer'</span>)</span><br></pre></td></tr></table></figure>
<p>finally子句</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br><span class="line">35</span><br><span class="line">36</span><br><span class="line">37</span><br><span class="line">38</span><br><span class="line">39</span><br><span class="line">40</span><br><span class="line">41</span><br><span class="line">42</span><br><span class="line">43</span><br><span class="line">44</span><br><span class="line">45</span><br><span class="line">46</span><br><span class="line">47</span><br><span class="line">48</span><br><span class="line">49</span><br><span class="line">50</span><br><span class="line">51</span><br><span class="line">52</span><br><span class="line">53</span><br><span class="line">54</span><br><span class="line">55</span><br><span class="line">56</span><br><span class="line">57</span><br><span class="line">58</span><br><span class="line">59</span><br><span class="line">60</span><br><span class="line">61</span><br><span class="line">62</span><br><span class="line">63</span><br><span class="line">64</span><br><span class="line">65</span><br><span class="line">66</span><br><span class="line">67</span><br><span class="line">68</span><br><span class="line">69</span><br><span class="line">70</span><br><span class="line">71</span><br><span class="line">72</span><br><span class="line">73</span><br><span class="line">74</span><br><span class="line">75</span><br><span class="line">76</span><br><span class="line">77</span><br><span class="line">78</span><br><span class="line">79</span><br><span class="line">80</span><br><span class="line">81</span><br><span class="line">82</span><br><span class="line">83</span><br><span class="line">84</span><br><span class="line">85</span><br><span class="line">86</span><br><span class="line">87</span><br><span class="line">88</span><br><span class="line">89</span><br><span class="line">90</span><br><span class="line">91</span><br><span class="line">92</span><br><span class="line">93</span><br><span class="line">94</span><br><span class="line">95</span><br><span class="line">96</span><br><span class="line">97</span><br><span class="line">98</span><br><span class="line">99</span><br><span class="line">100</span><br><span class="line">101</span><br><span class="line">102</span><br><span class="line">103</span><br><span class="line">104</span><br><span class="line">105</span><br><span class="line">106</span><br><span class="line">107</span><br><span class="line">108</span><br><span class="line">109</span><br><span class="line">110</span><br><span class="line">111</span><br><span class="line">112</span><br><span class="line">113</span><br><span class="line">114</span><br><span class="line">115</span><br><span class="line">116</span><br><span class="line">117</span><br><span class="line">118</span><br><span class="line">119</span><br><span class="line">120</span><br><span class="line">121</span><br><span class="line">122</span><br><span class="line">123</span><br><span class="line">124</span><br><span class="line">125</span><br><span class="line">126</span><br><span class="line">127</span><br><span class="line">128</span><br><span class="line">129</span><br><span class="line">130</span><br><span class="line">131</span><br><span class="line">132</span><br><span class="line">133</span><br><span class="line">134</span><br><span class="line">135</span><br><span class="line">136</span><br><span class="line">137</span><br><span class="line">138</span><br><span class="line">139</span><br><span class="line">140</span><br><span class="line">141</span><br><span class="line">142</span><br><span class="line">143</span><br><span class="line">144</span><br><span class="line">145</span><br><span class="line">146</span><br><span class="line">147</span><br><span class="line">148</span><br><span class="line">149</span><br><span class="line">150</span><br><span class="line">151</span><br><span class="line">152</span><br><span class="line">153</span><br><span class="line">154</span><br><span class="line">155</span><br><span class="line">156</span><br><span class="line">157</span><br><span class="line">158</span><br><span class="line">159</span><br><span class="line">160</span><br><span class="line">161</span><br><span class="line">162</span><br><span class="line">163</span><br><span class="line">164</span><br><span class="line">165</span><br><span class="line">166</span><br><span class="line">167</span><br><span class="line">168</span><br><span class="line">169</span><br><span class="line">170</span><br><span class="line">171</span><br><span class="line">172</span><br><span class="line">173</span><br><span class="line">174</span><br><span class="line">175</span><br><span class="line">176</span><br><span class="line">177</span><br><span class="line">178</span><br><span class="line">179</span><br><span class="line">180</span><br><span class="line">181</span><br><span class="line">182</span><br><span class="line">183</span><br><span class="line">184</span><br><span class="line">185</span><br><span class="line">186</span><br><span class="line">187</span><br><span class="line">188</span><br><span class="line">189</span><br><span class="line">190</span><br><span class="line">191</span><br><span class="line">192</span><br><span class="line">193</span><br><span class="line">194</span><br><span class="line">195</span><br><span class="line">196</span><br><span class="line">197</span><br><span class="line">198</span><br><span class="line">199</span><br><span class="line">200</span><br><span class="line">201</span><br><span class="line">202</span><br><span class="line">203</span><br><span class="line">204</span><br><span class="line">205</span><br><span class="line">206</span><br><span class="line">207</span><br></pre></td><td class="code"><pre><span class="line">如果有<span class="keyword">finally</span>，不管是否捕获到异常，都会执行<span class="keyword">finally</span>语句。它的作用是在运行中或运行结束后清理资源，清理工作放在这里，以释放资源。<span class="keyword">finally</span>与捕获异常没有关系，没有<span class="keyword">except</span>语句也可以。</span><br><span class="line"><span class="keyword">try</span>不会开辟新的作用域，在<span class="keyword">try</span>中和<span class="keyword">try</span>外面定义的变量效果是一样的，但不要在<span class="keyword">try</span>中定义，这是不好的习惯</span><br><span class="line"><span class="class"><span class="keyword">class</span> <span class="title">MyException</span><span class="params">(Exception)</span>:</span></span><br><span class="line">    <span class="keyword">pass</span></span><br><span class="line"></span><br><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    <span class="keyword">raise</span> MyException()</span><br><span class="line"><span class="keyword">except</span> Exception:</span><br><span class="line">    print(MyException.mro())</span><br><span class="line"></span><br><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    <span class="comment"># 1/0</span></span><br><span class="line">    <span class="keyword">raise</span> MyException</span><br><span class="line"></span><br><span class="line"><span class="keyword">except</span> MyException <span class="keyword">as</span> e:</span><br><span class="line">    print(<span class="string">'~~~~~~~~~~~~~~~~~'</span>)</span><br><span class="line">    print(e, type(e))</span><br><span class="line"><span class="keyword">except</span> OSError <span class="keyword">as</span> e:</span><br><span class="line">    print(<span class="string">'InterruptedError'</span>)</span><br><span class="line"><span class="keyword">except</span> Exception <span class="keyword">as</span> e:</span><br><span class="line">    print(e, type(e))</span><br><span class="line"></span><br><span class="line"><span class="keyword">finally</span>:  <span class="comment"># 异常可以被捕获到，处理完异常后会执行这里的finally</span></span><br><span class="line">    print(<span class="string">'fin'</span>)</span><br><span class="line"></span><br><span class="line">print(<span class="string">'outer'</span>)</span><br><span class="line">输出：</span><br><span class="line">[&lt;class '__main__.MyException'&gt;, &lt;class 'Exception'&gt;, &lt;class 'BaseException'&gt;, &lt;class 'object'&gt;]</span><br><span class="line">~~~~~~~~~~~~~~~~~</span><br><span class="line"> &lt;<span class="class"><span class="keyword">class</span> '<span class="title">__main__</span>.<span class="title">MyException</span>'&gt;</span></span><br><span class="line"><span class="class"><span class="title">fin</span></span></span><br><span class="line"><span class="class"><span class="title">outer</span></span></span><br><span class="line">===========================================================================================</span><br><span class="line"><span class="class"><span class="keyword">class</span> <span class="title">MyException</span><span class="params">(Exception)</span>:</span></span><br><span class="line">    <span class="keyword">pass</span></span><br><span class="line"></span><br><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    <span class="keyword">raise</span> MyException()</span><br><span class="line"><span class="keyword">except</span> Exception:</span><br><span class="line">    print(MyException.mro())</span><br><span class="line"></span><br><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    <span class="number">1</span>/<span class="number">0</span></span><br><span class="line">    <span class="keyword">raise</span> MyException</span><br><span class="line"></span><br><span class="line"><span class="keyword">except</span> MyException <span class="keyword">as</span> e:</span><br><span class="line">    print(<span class="string">'~~~~~~~~~~~~~~~~~'</span>)</span><br><span class="line">    print(e, type(e))</span><br><span class="line"><span class="keyword">except</span> OSError <span class="keyword">as</span> e:</span><br><span class="line">    print(<span class="string">'InterruptedError'</span>)</span><br><span class="line"><span class="comment"># 上面两个except没法捕获到异常，异常会抛给当前解释器，解释器会终止当前程序运行</span></span><br><span class="line"><span class="comment"># except Exception as e:</span></span><br><span class="line"><span class="comment">#     print(e, type(e))</span></span><br><span class="line"></span><br><span class="line"><span class="keyword">finally</span>:  <span class="comment"># 虽然异常抛给了解释器并终止了当前程序运行，但这一句还是运行了</span></span><br><span class="line">    print(<span class="string">'fin'</span>)</span><br><span class="line"></span><br><span class="line">print(<span class="string">'outer'</span>)  <span class="comment"># 因为解释器终止了当前程序运行，这一句没有执行到</span></span><br><span class="line">输出：</span><br><span class="line">[&lt;class '__main__.MyException'&gt;, &lt;class 'Exception'&gt;, &lt;class 'BaseException'&gt;, &lt;class 'object'&gt;]</span><br><span class="line">fin</span><br><span class="line">Traceback (most recent call last):</span><br><span class="line">  File <span class="string">"/home/shouyu/PycharmProjects/test/异常处理.py"</span>, line <span class="number">64</span>, <span class="keyword">in</span> &lt;module&gt;</span><br><span class="line">    <span class="number">1</span>/<span class="number">0</span></span><br><span class="line">ZeroDivisionError: division by zero</span><br><span class="line">===========================================================================================</span><br><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    f = open(<span class="string">'test1'</span>)  <span class="comment"># 这里会抛出一个OS的异常，不会赋值给f</span></span><br><span class="line"></span><br><span class="line"><span class="keyword">finally</span>:</span><br><span class="line">    f.close()</span><br><span class="line"></span><br><span class="line">print(<span class="string">'outer'</span>)</span><br><span class="line">输出：</span><br><span class="line">Traceback (most recent call last):</span><br><span class="line">  File <span class="string">"/home/shouyu/PycharmProjects/test/异常处理.py"</span>, line <span class="number">66</span>, <span class="keyword">in</span> &lt;module&gt;</span><br><span class="line">    f = open(<span class="string">'test1'</span>)</span><br><span class="line">FileNotFoundError: [Errno <span class="number">2</span>] No such file <span class="keyword">or</span> directory: <span class="string">'test1'</span></span><br><span class="line"></span><br><span class="line">During handling of the above exception, another exception occurred:</span><br><span class="line"></span><br><span class="line">Traceback (most recent call last):</span><br><span class="line">  File <span class="string">"/home/shouyu/PycharmProjects/test/异常处理.py"</span>, line <span class="number">78</span>, <span class="keyword">in</span> &lt;module&gt;</span><br><span class="line">    f.close()</span><br><span class="line">NameError: name <span class="string">'f'</span> <span class="keyword">is</span> <span class="keyword">not</span> defined </span><br><span class="line"><span class="comment"># 这里提示f没有被定义过，原因是在f = open('test1')就已经报错了，因为没有test1文件，所以不会打开，会抛异</span></span><br><span class="line"><span class="comment"># 常，也就不会给f赋值，所以f只是一个标识符，所以下面调用f.close的时候会提示f没有被定义过</span></span><br><span class="line">===========================================================================================</span><br><span class="line">f = <span class="keyword">None</span>   <span class="comment"># 这样做可以保证f被定义过，下面调用时就不会提示没有定义过了</span></span><br><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    f = open(<span class="string">'test1'</span>)</span><br><span class="line"></span><br><span class="line"><span class="keyword">finally</span>:</span><br><span class="line">    <span class="keyword">if</span> f <span class="keyword">is</span> <span class="keyword">not</span> <span class="keyword">None</span>:</span><br><span class="line">    	f.close()   <span class="comment"># 这里不能直播用f.close()，因为f是None的时候不能close，也会报错</span></span><br><span class="line"></span><br><span class="line">print(<span class="string">'outer'</span>)</span><br><span class="line">===========================================================================================</span><br><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    f = <span class="keyword">None</span>  <span class="comment"># 放在这里也可以，下面调用时不会报没有定义的异常</span></span><br><span class="line">    f = open(<span class="string">'test1'</span>)</span><br><span class="line"></span><br><span class="line"><span class="keyword">finally</span>:</span><br><span class="line">    <span class="keyword">if</span> f <span class="keyword">is</span> <span class="keyword">not</span> <span class="keyword">None</span>:</span><br><span class="line">    	f.close()   <span class="comment"># 这里不能直播用f.close()，因为f是None的时候不能close，也会报错</span></span><br><span class="line"></span><br><span class="line">print(<span class="string">'outer'</span>)</span><br><span class="line">输出：</span><br><span class="line">Traceback (most recent call last):</span><br><span class="line">  File <span class="string">"/home/shouyu/PycharmProjects/test/异常处理.py"</span>, line <span class="number">67</span>, <span class="keyword">in</span> &lt;module&gt;</span><br><span class="line">    f = open(<span class="string">'test1'</span>)</span><br><span class="line">FileNotFoundError: [Errno <span class="number">2</span>] No such file <span class="keyword">or</span> directory: <span class="string">'test1'</span></span><br><span class="line">===========================================================================================</span><br><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    f = <span class="keyword">None</span>  <span class="comment"># 放在这里也可以，下面调用时不会报没有定义的异常</span></span><br><span class="line">    f = open(<span class="string">'test1'</span>)</span><br><span class="line">    </span><br><span class="line"><span class="keyword">except</span>:  <span class="comment"># 这样定义的话连异常都看不到了</span></span><br><span class="line">    <span class="keyword">pass</span></span><br><span class="line"></span><br><span class="line"><span class="keyword">finally</span>:</span><br><span class="line">    <span class="keyword">if</span> f <span class="keyword">is</span> <span class="keyword">not</span> <span class="keyword">None</span>:</span><br><span class="line">    	f.close()   <span class="comment"># 这里不能直播用f.close()，因为f是None的时候不能close，也会报错</span></span><br><span class="line"></span><br><span class="line">print(<span class="string">'outer'</span>)</span><br><span class="line">print(dir())</span><br><span class="line"><span class="comment"># dir()表示收集当前环境的变量，可以看到有f，这说明try不会影响当前作用域名，在try中定义的f和在try外面定义f是一样的，但最好不要将f定义写在try中</span></span><br><span class="line">输出：</span><br><span class="line">outer</span><br><span class="line">[ <span class="string">'__annotations__'</span>, <span class="string">'__builtins__'</span>, <span class="string">'__cached__'</span>, <span class="string">'__doc__'</span>, <span class="string">'__file__'</span>, <span class="string">'__loader__'</span>, <span class="string">'__name__'</span>, <span class="string">'__package__'</span>, <span class="string">'__spec__'</span>, <span class="string">'f'</span>]</span><br><span class="line">===========================================================================================</span><br><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    f = <span class="keyword">None</span>  <span class="comment"># 放在这里也可以，下面调用时不会报没有定义的异常</span></span><br><span class="line">    f = open(<span class="string">'test1'</span>)</span><br><span class="line">    </span><br><span class="line"><span class="keyword">except</span>:  <span class="comment"># 这样定义的话连异常都看不到了</span></span><br><span class="line">    <span class="keyword">pass</span></span><br><span class="line"></span><br><span class="line"><span class="keyword">finally</span>:</span><br><span class="line">    <span class="keyword">try</span>:</span><br><span class="line">        f.close()  <span class="comment"># 这里不关心是否出现异常，只是要关闭资源，但如果上面因为没有test1而抛出异常，这里关闭也会出现问题，所以用try捕获异常并交给下面的except处理</span></span><br><span class="line">    <span class="keyword">except</span>:</span><br><span class="line">        <span class="keyword">pass</span></span><br><span class="line"></span><br><span class="line">print(<span class="string">'outer'</span>)</span><br><span class="line">print(dir())</span><br><span class="line">===========================================================================================</span><br><span class="line"><span class="function"><span class="keyword">def</span> <span class="title">foo</span><span class="params">()</span>:</span></span><br><span class="line">    <span class="keyword">try</span>:</span><br><span class="line">        <span class="keyword">return</span> <span class="number">1</span></span><br><span class="line"></span><br><span class="line">    <span class="keyword">except</span>:</span><br><span class="line">        <span class="keyword">pass</span></span><br><span class="line"></span><br><span class="line">    <span class="keyword">finally</span>:</span><br><span class="line">        print(<span class="string">'fin'</span>)</span><br><span class="line"></span><br><span class="line">foo()</span><br><span class="line">print(<span class="string">'outer'</span>)</span><br><span class="line">print(dir())</span><br><span class="line"><span class="comment"># 从输出可以看出没有拿到return 1的结果</span></span><br><span class="line">输出： </span><br><span class="line">fin</span><br><span class="line">outer</span><br><span class="line">[<span class="string">'__annotations__'</span>, <span class="string">'__builtins__'</span>, <span class="string">'__cached__'</span>, <span class="string">'__doc__'</span>, <span class="string">'__file__'</span>, <span class="string">'__loader__'</span>, <span class="string">'__name__'</span>, <span class="string">'__package__'</span>, <span class="string">'__spec__'</span>, <span class="string">'foo'</span>]</span><br><span class="line">===========================================================================================</span><br><span class="line"><span class="function"><span class="keyword">def</span> <span class="title">foo</span><span class="params">()</span>:</span></span><br><span class="line">    <span class="keyword">try</span>:</span><br><span class="line">        <span class="number">1</span>/<span class="number">0</span></span><br><span class="line">        <span class="keyword">return</span> <span class="number">1</span></span><br><span class="line"></span><br><span class="line">    <span class="keyword">except</span>:</span><br><span class="line">        <span class="keyword">pass</span></span><br><span class="line"></span><br><span class="line">    <span class="keyword">finally</span>:</span><br><span class="line">        print(<span class="string">'fin'</span>)</span><br><span class="line"></span><br><span class="line"><span class="comment"># print("result = " + foo())  </span></span><br><span class="line"><span class="comment"># 不能这样写，因为执行到1/0时就会抛出异常，不会执行return语句，foo()返回的也就是None，用字符串加None会报错：TypeError: can only concatenate str (not "NoneType") to str</span></span><br><span class="line">print(<span class="string">"result = &#123;&#125;"</span>.format(foo())) <span class="comment"># 写成这样就没有问题了</span></span><br><span class="line">print(<span class="string">'outer'</span>)</span><br><span class="line">输出：</span><br><span class="line">fin</span><br><span class="line">result = <span class="keyword">None</span></span><br><span class="line">outer</span><br><span class="line">===========================================================================================</span><br><span class="line"><span class="function"><span class="keyword">def</span> <span class="title">foo</span><span class="params">()</span>:</span></span><br><span class="line">    <span class="keyword">try</span>:</span><br><span class="line">        <span class="comment"># 1/0</span></span><br><span class="line">        <span class="keyword">return</span> <span class="number">123</span></span><br><span class="line"></span><br><span class="line">    <span class="keyword">except</span>:</span><br><span class="line">        <span class="keyword">pass</span></span><br><span class="line"></span><br><span class="line">    <span class="keyword">finally</span>:</span><br><span class="line">        <span class="keyword">return</span> <span class="number">567</span>   <span class="comment"># 一般不会在finally里return，可以在这里用try和except</span></span><br><span class="line"><span class="comment"># 从输出结果可以看出，这里的return覆盖了上面try中的return，下面的print('fin')也不会执行了。</span></span><br><span class="line"><span class="comment"># 无论如何，最后都要执行finally，在自解码时，会把最后一条return值放在栈顶，函数返回值会从栈顶拿，所以输出</span></span><br><span class="line"><span class="comment"># 是567，剩下的栈里的值清空，函数执行结束。函数调用的时候，把函数加载到栈里创建临时变量，然后计算，计算完以</span></span><br><span class="line"><span class="comment"># 后把栈顶的值return回去，之后清空栈里的东西</span></span><br><span class="line">        print(<span class="string">'fin'</span>)</span><br><span class="line"></span><br><span class="line">print(<span class="string">"result = &#123;&#125;"</span>.format(foo()))</span><br><span class="line">print(<span class="string">'outer'</span>)</span><br><span class="line">输出：</span><br><span class="line">result = <span class="number">567</span></span><br><span class="line">outer</span><br></pre></td></tr></table></figure>
<p>异常的传递</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br><span class="line">35</span><br><span class="line">36</span><br><span class="line">37</span><br><span class="line">38</span><br><span class="line">39</span><br><span class="line">40</span><br><span class="line">41</span><br><span class="line">42</span><br><span class="line">43</span><br><span class="line">44</span><br><span class="line">45</span><br><span class="line">46</span><br><span class="line">47</span><br><span class="line">48</span><br><span class="line">49</span><br><span class="line">50</span><br><span class="line">51</span><br><span class="line">52</span><br><span class="line">53</span><br><span class="line">54</span><br><span class="line">55</span><br><span class="line">56</span><br><span class="line">57</span><br><span class="line">58</span><br><span class="line">59</span><br><span class="line">60</span><br><span class="line">61</span><br><span class="line">62</span><br><span class="line">63</span><br><span class="line">64</span><br><span class="line">65</span><br><span class="line">66</span><br><span class="line">67</span><br><span class="line">68</span><br><span class="line">69</span><br><span class="line">70</span><br><span class="line">71</span><br><span class="line">72</span><br><span class="line">73</span><br><span class="line">74</span><br><span class="line">75</span><br><span class="line">76</span><br><span class="line">77</span><br><span class="line">78</span><br><span class="line">79</span><br><span class="line">80</span><br><span class="line">81</span><br><span class="line">82</span><br><span class="line">83</span><br><span class="line">84</span><br><span class="line">85</span><br><span class="line">86</span><br><span class="line">87</span><br><span class="line">88</span><br><span class="line">89</span><br><span class="line">90</span><br><span class="line">91</span><br><span class="line">92</span><br><span class="line">93</span><br><span class="line">94</span><br><span class="line">95</span><br><span class="line">96</span><br><span class="line">97</span><br><span class="line">98</span><br><span class="line">99</span><br><span class="line">100</span><br><span class="line">101</span><br><span class="line">102</span><br><span class="line">103</span><br><span class="line">104</span><br><span class="line">105</span><br><span class="line">106</span><br><span class="line">107</span><br><span class="line">108</span><br><span class="line">109</span><br><span class="line">110</span><br><span class="line">111</span><br><span class="line">112</span><br><span class="line">113</span><br><span class="line">114</span><br><span class="line">115</span><br><span class="line">116</span><br><span class="line">117</span><br><span class="line">118</span><br><span class="line">119</span><br><span class="line">120</span><br><span class="line">121</span><br><span class="line">122</span><br><span class="line">123</span><br><span class="line">124</span><br><span class="line">125</span><br><span class="line">126</span><br><span class="line">127</span><br><span class="line">128</span><br><span class="line">129</span><br><span class="line">130</span><br><span class="line">131</span><br><span class="line">132</span><br><span class="line">133</span><br><span class="line">134</span><br><span class="line">135</span><br><span class="line">136</span><br><span class="line">137</span><br><span class="line">138</span><br><span class="line">139</span><br><span class="line">140</span><br><span class="line">141</span><br><span class="line">142</span><br><span class="line">143</span><br><span class="line">144</span><br><span class="line">145</span><br><span class="line">146</span><br><span class="line">147</span><br><span class="line">148</span><br><span class="line">149</span><br><span class="line">150</span><br></pre></td><td class="code"><pre><span class="line"><span class="comment"># Traceback是回溯的意思，可以查看都经过了哪些步骤，像是traceroute</span></span><br><span class="line"><span class="comment"># 当调用foo2时就会调用foo1，调用foo1时就会产生异常，但这个异常没有处理机制，这时异常就会抛给调用foo1的函数。从抛出的异常可以看到，异常是1/0抛出的，这个异常是foo1调用的时候产生的，foo1是在foo2调用时产生的，这样就可以找到源头了</span></span><br><span class="line"><span class="function"><span class="keyword">def</span> <span class="title">foo1</span><span class="params">()</span>:</span></span><br><span class="line">    <span class="keyword">try</span>:</span><br><span class="line">        <span class="number">1</span>/<span class="number">0</span></span><br><span class="line"></span><br><span class="line">    <span class="keyword">finally</span>:</span><br><span class="line">        print(<span class="string">'fin'</span>)</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">def</span> <span class="title">foo2</span><span class="params">()</span>:</span></span><br><span class="line">    foo1()</span><br><span class="line"></span><br><span class="line">foo2()</span><br><span class="line">print(<span class="string">'outer'</span>)</span><br><span class="line">输出：</span><br><span class="line">fin</span><br><span class="line">Traceback (most recent call last):</span><br><span class="line">  File <span class="string">"/home/shouyu/PycharmProjects/test/异常处理.py"</span>, line <span class="number">111</span>, <span class="keyword">in</span> &lt;module&gt;</span><br><span class="line">    foo2()</span><br><span class="line">  File <span class="string">"/home/shouyu/PycharmProjects/test/异常处理.py"</span>, line <span class="number">109</span>, <span class="keyword">in</span> foo2</span><br><span class="line">    foo1()</span><br><span class="line">  File <span class="string">"/home/shouyu/PycharmProjects/test/异常处理.py"</span>, line <span class="number">103</span>, <span class="keyword">in</span> foo1</span><br><span class="line">    <span class="number">1</span>/<span class="number">0</span></span><br><span class="line">ZeroDivisionError: division by zero</span><br><span class="line">===========================================================================================</span><br><span class="line"><span class="function"><span class="keyword">def</span> <span class="title">foo1</span><span class="params">()</span>:</span></span><br><span class="line">    <span class="keyword">try</span>:</span><br><span class="line">        <span class="number">1</span>/<span class="number">0</span></span><br><span class="line"></span><br><span class="line">    <span class="keyword">finally</span>:</span><br><span class="line">        print(<span class="string">'foo1 fin'</span>)</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">def</span> <span class="title">foo2</span><span class="params">()</span>:</span>  <span class="comment"># 可以在这个函数中捕获异常</span></span><br><span class="line">    <span class="keyword">try</span>:</span><br><span class="line">        foo1()</span><br><span class="line">    <span class="keyword">except</span> Exception <span class="keyword">as</span> e:</span><br><span class="line">        print(e)</span><br><span class="line">        </span><br><span class="line">    <span class="keyword">finally</span>:  <span class="comment"># 如果注释上面的except，异常就不会被处理，会报错，这里会打印foo2 fin。抛出的错误给到了解释器，解释器会中断函数的执行并抛出错误</span></span><br><span class="line">        print(<span class="string">'foo2 fin'</span>)</span><br><span class="line"></span><br><span class="line"><span class="keyword">try</span>:  <span class="comment"># 当函数中都不处理异常时，会抛给解释器，可以在这里加入异常的处理办法，这样就不会抛出异常了</span></span><br><span class="line">    foo2()</span><br><span class="line"><span class="keyword">except</span> Exception <span class="keyword">as</span> e:</span><br><span class="line">    print(e)</span><br><span class="line"><span class="keyword">finally</span>:</span><br><span class="line">    print(<span class="string">'outer fin'</span>)</span><br><span class="line">print(<span class="string">'outer'</span>)</span><br><span class="line">输出：</span><br><span class="line">fin</span><br><span class="line">division by zero</span><br><span class="line">outer</span><br><span class="line">===========================================================================================</span><br><span class="line">不要认为<span class="keyword">except</span>或<span class="keyword">finally</span>是安全的，只要不处理异常就会往外抛</span><br><span class="line"><span class="keyword">try</span>是捕获异常的，<span class="keyword">except</span>是匹配异常并处理的，<span class="keyword">finally</span>是清理资源的</span><br><span class="line"><span class="function"><span class="keyword">def</span> <span class="title">foo1</span><span class="params">()</span>:</span></span><br><span class="line">    <span class="keyword">try</span>:</span><br><span class="line">        <span class="number">1</span>/<span class="number">0</span></span><br><span class="line"></span><br><span class="line">    <span class="keyword">finally</span>:</span><br><span class="line">        print(<span class="string">'foo1 fin'</span>)</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">def</span> <span class="title">foo2</span><span class="params">()</span>:</span></span><br><span class="line">    <span class="keyword">try</span>:</span><br><span class="line">        foo1()</span><br><span class="line">    <span class="keyword">except</span> Exception <span class="keyword">as</span> e:</span><br><span class="line">        print(<span class="string">"foo2 deal"</span>)  <span class="comment"># 这里会处理</span></span><br><span class="line">        <span class="keyword">raise</span> e  <span class="comment"># 这是为了让外层知道内部处理过什么异常</span></span><br><span class="line">    <span class="keyword">finally</span>:</span><br><span class="line">        print(<span class="string">'foo2 fin'</span>)</span><br><span class="line"></span><br><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    foo2()</span><br><span class="line"><span class="keyword">except</span> Exception <span class="keyword">as</span> e:</span><br><span class="line">    print(<span class="string">"outer"</span>, e)  <span class="comment"># 这里不会处理，也就是内部处理掉，外部就不会知道有这个异常</span></span><br><span class="line"><span class="keyword">finally</span>:</span><br><span class="line">    print(<span class="string">'outer fin'</span>)</span><br><span class="line"></span><br><span class="line">print(<span class="string">'outer'</span>)</span><br><span class="line">输出：</span><br><span class="line">foo1 fin</span><br><span class="line">foo2 deal</span><br><span class="line">foo2 fin</span><br><span class="line">outer fin</span><br><span class="line">outer</span><br><span class="line">===========================================================================================</span><br><span class="line"><span class="keyword">import</span> sys</span><br><span class="line"><span class="keyword">import</span> threading</span><br><span class="line"><span class="keyword">import</span> time</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">def</span> <span class="title">foo1</span><span class="params">()</span>:</span></span><br><span class="line">    <span class="keyword">try</span>:</span><br><span class="line">        <span class="number">1</span>/<span class="number">0</span></span><br><span class="line"></span><br><span class="line">    <span class="keyword">finally</span>:</span><br><span class="line">        print(<span class="string">'foo1 fin'</span>)</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">def</span> <span class="title">foo2</span><span class="params">()</span>:</span></span><br><span class="line">    time.sleep(<span class="number">4</span>)</span><br><span class="line">    <span class="keyword">try</span>:</span><br><span class="line">        foo1()</span><br><span class="line">    <span class="keyword">finally</span>:</span><br><span class="line">        print(<span class="string">'foo2 fin'</span>)</span><br><span class="line">        open(<span class="string">'abcde'</span>)</span><br><span class="line">    <span class="keyword">while</span> <span class="keyword">True</span>:  </span><br><span class="line"><span class="comment"># 如果foo2函数中的上面的语句不出问题，就会执行这一句，执行到这一句就进入一个死循环状态，死循环状态下这个函数</span></span><br><span class="line"><span class="comment"># 就不会退出，那么下面的t线程也就不会退出，t.is_alive也就一直是活着的</span></span><br><span class="line">        time.sleep(<span class="number">1</span>)</span><br><span class="line"></span><br><span class="line">t = threading.Thread(target=foo2)  <span class="comment"># 创建一个foo2线程</span></span><br><span class="line">t.start()  <span class="comment"># 启动线程</span></span><br><span class="line"><span class="comment"># 主线程一直在跑，t线程是一个分支。这段代码是为了测试当异常产生时，是结束了t线程，还是把主线程也一起结束了。当前线程是下面写的死循环</span></span><br><span class="line"></span><br><span class="line"><span class="keyword">while</span> <span class="keyword">True</span>:</span><br><span class="line">    time.sleep(<span class="number">1</span>)</span><br><span class="line">    print(<span class="string">'~~~~~~~~~~~~~~~~~~'</span>)</span><br><span class="line">    <span class="keyword">if</span> t.is_alive():</span><br><span class="line">        print(<span class="string">'alive'</span>)</span><br><span class="line">    <span class="keyword">else</span>:</span><br><span class="line">        print(<span class="string">'dead'</span>)</span><br><span class="line"><span class="comment"># 这段代码表示当前线程是一个死循环，每隔一秒查看一下t线程是否还活着。如果上面的foo2函数抛出异常，那么t线程也会结束</span></span><br><span class="line"></span><br><span class="line"><span class="comment"># 从执行的结果可以看出，对于一个异常来说，它是怎样进行传递的。它的异常是从它的产生地向外抛，如果没人管，继续向外抛，直至线程这一级，当它到了线程就是到了天花板了，如果没有代码管，当前线程就会结束，主线程不会有问题。也就是如果异常抛出后一路都没人管，会到当前线程，使当前线程中止，如果这个线程是主线程，那么主线程就会被中止，这会使到整个程序崩溃。</span></span><br><span class="line"><span class="comment"># 如果注释掉t线程，只用最外层的while True循环调用foo2()的话，是不会进入死循环的，会提示Process finished with exit code 1，表示当前解释器退出了</span></span><br><span class="line"><span class="comment"># try嵌套最多两层</span></span><br><span class="line">===========================================================================================</span><br><span class="line"><span class="comment"># 不要做这样吞掉异常，因为外部无法感知到异常</span></span><br><span class="line"><span class="keyword">import</span> sys</span><br><span class="line"><span class="keyword">import</span> threading</span><br><span class="line"><span class="keyword">import</span> time</span><br><span class="line"></span><br><span class="line"><span class="function"><span class="keyword">def</span> <span class="title">foo</span><span class="params">()</span>:</span></span><br><span class="line">    <span class="keyword">try</span>:</span><br><span class="line">        <span class="number">1</span>/<span class="number">0</span></span><br><span class="line">    <span class="keyword">finally</span>:</span><br><span class="line">        print(<span class="string">'foo1 fin'</span>)</span><br><span class="line">        <span class="keyword">return</span>   <span class="comment"># 这里return就会抛弃异常，直接退出了</span></span><br><span class="line"></span><br><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    foo()</span><br><span class="line"></span><br><span class="line"><span class="keyword">except</span> Exception <span class="keyword">as</span> e:  <span class="comment"># 因为上面抛弃了异常，所以不会执行到这里</span></span><br><span class="line">    print(<span class="string">'outer except'</span>, e)</span><br><span class="line"><span class="keyword">finally</span>:</span><br><span class="line">    print(<span class="string">'outer fin'</span>)</span><br><span class="line">print(<span class="string">'outer'</span>)</span><br><span class="line">输出：</span><br><span class="line">foo1 fin</span><br><span class="line">outer fin</span><br><span class="line">outer</span><br></pre></td></tr></table></figure>
<p>异常的捕获时机</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br></pre></td><td class="code"><pre><span class="line">立即捕获</span><br><span class="line"><span class="function"><span class="keyword">def</span> <span class="title">getaint</span><span class="params">(data)</span>:</span>  <span class="comment"># 请给一个整数，如果有问题就赋值为0</span></span><br><span class="line">    <span class="keyword">try</span>:  </span><br><span class="line">        res = int(data)</span><br><span class="line">    <span class="keyword">except</span> Exception:</span><br><span class="line">        res = <span class="number">0</span></span><br><span class="line">    <span class="keyword">return</span> res</span><br><span class="line"></span><br><span class="line">边界捕获</span><br></pre></td></tr></table></figure>
<p>else子句</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br></pre></td><td class="code"><pre><span class="line">如果<span class="keyword">try</span>中没有异常，就会执行<span class="keyword">else</span>子句，如果<span class="keyword">try</span>中有异常，就不会执行<span class="keyword">else</span>子句</span><br><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    <span class="number">1</span></span><br><span class="line"><span class="keyword">except</span> ArithmeticError:</span><br><span class="line">    print(<span class="string">'except'</span>)</span><br><span class="line"><span class="keyword">except</span>:</span><br><span class="line">    print(<span class="string">'except'</span>)</span><br><span class="line"><span class="keyword">else</span>:</span><br><span class="line">    print(<span class="string">'else'</span>)</span><br><span class="line">    </span><br><span class="line"><span class="keyword">finally</span>:</span><br><span class="line">    print(<span class="string">'fin'</span>)</span><br></pre></td></tr></table></figure>
<h3 id="总结-1"><a href="#总结-1" class="headerlink" title="总结"></a>总结</h3><ol>
<li><p>语法错误又称解析错误，解析器会输出出现语法错误的那一行，并显示一个向上的“箭头”，指向这行里面检测到的第一个错误。 错误是由箭头指示的位置 <em>上面</em> 的 token 引起的（或者至少是在这里被检测出的）。另外文件名和行号也会被输出，以便输入来自脚本文件时你能知道去哪检查。</p>
</li>
<li><p>语句或表达式在语法上是正确的，但在尝试执行时，它仍可能会引发错误。 在执行时检测到的错误被称为 <em>异常</em>，异常不一定会导致严重后果。但是，大多数异常并不会被程序处理，此时会显示错误信息</p>
<p>错误信息的最后一行告诉我们程序遇到了什么类型的错误。异常有不同的类型，而其类型名称将会作为错误信息的一部分打印出来。作为异常类型打印的字符串是发生的内置异常的名称。对于所有内置异常都是如此，但对于用户定义的异常则不一定如此。标准的异常类型是内置的标识符（而不是保留关键字）。</p>
<p>这一行的剩下的部分根据异常类型及其原因提供详细信息。</p>
<p>错误信息的前一部分以堆栈回溯的形式显示发生异常时的上下文。通常它包含列出源代码行的堆栈回溯；但是它不会显示从标准输入中读取的行。</p>
</li>
<li><p>可以编写处理所选异常的程序。请注意用户引起的中断可以通过引发<code>KeyboardInterrupt</code>异常来指示。</p>
</li>
<li><p>一个<code>try</code>语句可能有多个 except 子句，以指定不同异常的处理程序。 最多会执行一个处理程序。 处理程序只处理相应的 try 子句中发生的异常，而不处理同一 <code>try</code> 语句内其他处理程序中的异常。 一个 except 子句可以将多个异常命名为带括号的元组，如：<code>except (RuntimeError, TypeError, NameError): pass</code>。如果发生的异常和 <code>except</code> 子句中的类是同一个类或者是它的基类，则异常和 except 子句中的类是兼容的（但反过来则不成立 — 列出派生类的 except 子句与基类不兼容）。 except 子句可以省略异常名，以用作通配符。但请谨慎使用，因为以这种方式很容易掩盖真正的编程错误！它还可用于打印错误消息，然后重新引发异常（同样允许调用者处理异常）</p>
</li>
<li><p><code>try</code> … <code>except</code>语句有一个可选的 <em>else 子句</em>，在使用时必须放在所有的 except 子句后面。对于在try 子句不引发异常时必须执行的代码来说很有用。使用 <code>else</code> 子句比向 <code>try</code>子句添加额外的代码要好，因为它避免了意外捕获由 <code>try</code> … <code>except</code> 语句保护的代码未引发的异常。</p>
<p>发生异常时，它可能具有关联值，也称为异常 <em>参数</em> 。参数的存在和类型取决于异常类型。</p>
<p>except 子句可以在异常名称后面指定一个变量。这个变量和一个异常实例绑定，它的参数存储在 <code>instance.args</code> 中。为了方便起见，异常实例定义了<code>__str__()</code> ，因此可以直接打印参数而无需引用 <code>.args</code> 。也可以在抛出之前首先实例化异常，并根据需要向其添加任何属性。如果异常有参数，则它们将作为未处理异常的消息的最后一部分打印。</p>
<p>异常处理程序不仅处理 try 子句中遇到的异常，还处理 try 子句中调用（即使是间接地）的函数内部发生的异常。</p>
</li>
<li><p><code>raise</code>语句允许程序员强制发生指定的异常。<code>raise</code>唯一的参数就是要抛出的异常。这个参数必须是一个异常实例或者是一个异常类（派生自 <code>Exception</code>的类）。如果传递的是一个异常类，它将通过调用没有参数的构造函数来隐式实例化。如果你需要确定是否引发了异常但不打算处理它，则可以使用更简单的 <code>raise</code>语句形式重新引发异常</p>
</li>
<li><p>程序可以通过创建新的异常类来命名它们自己的异常。异常通常应该直接或间接地从 <code>Exception</code>类派生。</p>
<p>可以定义异常类，它可以执行任何其他类可以执行的任何操作，但通常保持简单，通常只提供许多属性，这些属性允许处理程序为异常提取有关错误的信息。在创建可能引发多个不同错误的模块时，通常的做法是为该模块定义的异常创建基类，并为不同错误条件创建特定异常类的子类</p>
<p>大多数异常都定义为名称以“Error”结尾，类似于标准异常的命名。</p>
<p>许多标准模块定义了它们自己的异常，以报告它们定义的函数中可能出现的错误。</p>
</li>
<li><p><code>try</code>语句有另一个可选子句，用于定义必须在所有情况下执行的清理操作。如果存在<code>finally</code>子句，则 <code>finally</code> 子句将作为<code>try</code>语句结束前的最后一项任务被执行。 <code>finally</code> 子句不论 <code>try</code> 语句是否产生了异常都会被执行。<code>finally</code>子句在任何情况下都会被执行。 两个字符串相除所引发的<code>TypeError</code>不会由<code>except</code>子句处理，因此会在 <code>finally</code> 子句执行后被重新引发。</p>
<p>在实际应用程序中，<code>finally</code>子句对于释放外部资源（例如文件或者网络连接）非常有用，无论是否成功使用资源。</p>
</li>
</ol>
<h4 id="try语句的工作原理如下："><a href="#try语句的工作原理如下：" class="headerlink" title="try语句的工作原理如下："></a>try语句的工作原理如下：</h4><ul>
<li>首先，执行 <em>try 子句</em> （<code>try</code> 和 <code>except</code>关键字之间的（多行）语句）。</li>
<li>如果没有异常发生，则跳过 <em>except 子句</em> 并完成 <code>try</code>语句的执行。</li>
<li>如果在执行try 子句时发生了异常，则跳过该子句中剩下的部分。然后，如果异常的类型和<code>except</code>关键字后面的异常匹配，则执行 except 子句 ，然后继续执行<code>try</code>语句之后的代码。</li>
<li>如果发生的异常和 except 子句中指定的异常不匹配，则将其传递到外部的<code>try</code>语句中；如果没有找到处理程序，则它是一个 <em>未处理异常</em>，执行将停止并显示如上所示的消息。</li>
<li><strong>没有任何异常发生</strong>时执行<code>else</code>子句</li>
<li>如果在执行 <code>try</code> 子句期间发生了异常，该异常可由一个<code>except</code>子句进行处理。 如果异常没有被某个 <code>except</code> 子句所处理，则该异常会在 <code>finally</code> 子句执行之后被重新引发。</li>
<li>异常也可能在 <code>except</code> 或 <code>else</code> 子句执行期间发生。 同样地，该异常会在 <code>finally</code> 子句执行之后被重新引发。</li>
<li>如果在执行 <code>try</code> 语句时遇到一个<code>break</code>，<code>continue</code>或<code>return</code>语句，则 <code>finally</code> 子句将在执行 <code>break</code>, <code>continue</code> 或 <code>return</code> 语句之前被执行。</li>
<li>如果 <code>finally</code> 子句中包含一个 <code>return</code> 语句，则返回值将来自 <code>finally</code> 子句的某个 <code>return</code> 语句的返回值，而非来自 <code>try</code> 子句的 <code>return</code> 语句的返回值。</li>
</ul>
<h4 id="raise用法"><a href="#raise用法" class="headerlink" title="raise用法"></a>raise用法</h4><p>raise 语句的基本语法格式为：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">raise</span> [exceptionName [(reason)]]</span><br></pre></td></tr></table></figure>
<p>raise 语句有如下三种常用的用法：</p>
<ol>
<li>raise：单独一个 raise。该语句引发当前上下文中捕获的异常（比如在 except 块中），或默认引发 <code>RuntimeError</code> 异常。</li>
<li>raise 异常类名称：raise 后带一个异常类名称，表示引发执行类型的异常。</li>
<li>raise 异常类名称(描述信息)：在引发指定类型的异常的同时，附带异常的描述信息。</li>
</ol>
<p>举例：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    a = input(<span class="string">"输入一个数："</span>)</span><br><span class="line">    <span class="comment">#判断用户输入的是否为数字</span></span><br><span class="line">    <span class="keyword">if</span>(<span class="keyword">not</span> a.isdigit()):</span><br><span class="line">        <span class="keyword">raise</span> ValueError(<span class="string">"a 必须是数字"</span>)  <span class="comment"># 这个手动抛出的异常会被try捕获，之后在except中处理</span></span><br><span class="line"><span class="keyword">except</span> ValueError <span class="keyword">as</span> e:</span><br><span class="line">    print(<span class="string">"引发异常："</span>,repr(e))</span><br><span class="line">    <span class="keyword">raise</span></span><br><span class="line">输出：</span><br><span class="line">输入一个数：a</span><br><span class="line">引发异常： ValueError(<span class="string">'a 必须是数字'</span>,)</span><br><span class="line">Traceback (most recent call last):</span><br><span class="line">  File <span class="string">"D:\python3.6\1.py"</span>, line <span class="number">4</span>, <span class="keyword">in</span> &lt;module&gt;</span><br><span class="line">    <span class="keyword">raise</span> ValueError(<span class="string">"a 必须是数字"</span>)</span><br><span class="line">ValueError: a 必须是数字</span><br><span class="line">    </span><br><span class="line"><span class="comment"># 当用户输入的不是数字时，程序会进入 if 判断语句，并执行 raise 引发 ValueError 异常。但由于其位于 try 块</span></span><br><span class="line"><span class="comment"># 中，因为 raise 抛出的异常会被 try 捕获，并由 except 块进行处理。</span></span><br><span class="line"><span class="comment"># 这里重点关注位于 except 块中的 raise，由于在其之前我们已经手动引发了 ValueError 异常，因此这里当再使用</span></span><br><span class="line"><span class="comment"># raise 语句时，它会再次引发一次。</span></span><br><span class="line"></span><br><span class="line">当在没有引发过异常的程序使用无参的 <span class="keyword">raise</span> 语句时，它默认引发的是 RuntimeError 异常。如下：</span><br><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    a = input(<span class="string">"输入一个数："</span>)</span><br><span class="line">    <span class="keyword">if</span>(<span class="keyword">not</span> a.isdigit()):</span><br><span class="line">        <span class="keyword">raise</span></span><br><span class="line"><span class="keyword">except</span> RuntimeError <span class="keyword">as</span> e:</span><br><span class="line">    print(<span class="string">"引发异常："</span>,repr(e))</span><br><span class="line">输出：</span><br><span class="line">输入一个数：a</span><br><span class="line">引发异常： RuntimeError(<span class="string">'No active exception to reraise'</span>,)</span><br></pre></td></tr></table></figure>

      
    </div>

    

    
    
    

    

    

    

    <footer class="post-footer">
      
        <div class="post-tags">
          
            <a href="/tags/python异常处理/" rel="tag"># python异常处理</a>
          
        </div>
      

      
      
      

      
        <div class="post-nav">
          <div class="post-nav-next post-nav-item">
            
              <a href="/2020/04/27/python总结-装饰器/" rel="next" title="python总结_装饰器">
                <i class="fa fa-chevron-left"></i> python总结_装饰器
              </a>
            
          </div>

          <span class="post-nav-divider"></span>

          <div class="post-nav-prev post-nav-item">
            
              <a href="/2020/05/04/python基础学习-模块化/" rel="prev" title="python基础学习-模块化">
                python基础学习-模块化 <i class="fa fa-chevron-right"></i>
              </a>
            
          </div>
        </div>
      

      
      
    </footer>
  </div>
  
  
  
  </article>


  </div>


          </div>
          

  


        </div>
        
          
  
  <div class="sidebar-toggle">
    <div class="sidebar-toggle-line-wrap">
      <span class="sidebar-toggle-line sidebar-toggle-line-first"></span>
      <span class="sidebar-toggle-line sidebar-toggle-line-middle"></span>
      <span class="sidebar-toggle-line sidebar-toggle-line-last"></span>
    </div>
  </div>

  <aside id="sidebar" class="sidebar">
    
    <div class="sidebar-inner">

      

      
        <ul class="sidebar-nav motion-element">
          <li class="sidebar-nav-toc sidebar-nav-active" data-target="post-toc-wrap">
            文章目錄
          </li>
          <li class="sidebar-nav-overview" data-target="site-overview-wrap">
            本站概要
          </li>
        </ul>
      

      <section class="site-overview-wrap sidebar-panel">
        <div class="site-overview">
          <div class="site-author motion-element" itemprop="author" itemscope itemtype="http://schema.org/Person">
            
              <p class="site-author-name" itemprop="name">ruopu</p>
              <p class="site-description motion-element" itemprop="description"></p>
          </div>

          
            <nav class="site-state motion-element">
              
                <div class="site-state-item site-state-posts">
                
                  <a href="/archives/">
                
                    <span class="site-state-item-count">247</span>
                    <span class="site-state-item-name">文章</span>
                  </a>
                </div>
              

              
                
                
                <div class="site-state-item site-state-categories">
                  <a href="/categories/index.html">
                    
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                    <span class="site-state-item-count">32</span>
                    <span class="site-state-item-name">分類</span>
                  </a>
                </div>
              

              
                
                
                <div class="site-state-item site-state-tags">
                  <a href="/tags/index.html">
                    
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                    <span class="site-state-item-count">176</span>
                    <span class="site-state-item-name">標籤</span>
                  </a>
                </div>
              
            </nav>
          

          

          

          
          

          
          

          
            
          
          

        </div>
      </section>

      
      <!--noindex-->
        <section class="post-toc-wrap motion-element sidebar-panel sidebar-panel-active">
          <div class="post-toc">

            
              
            

            
              <div class="post-toc-content"><ol class="nav"><li class="nav-item nav-level-3"><a class="nav-link" href="#异常处理-Exception"><span class="nav-number">1.</span> <span class="nav-text">异常处理 Exception</span></a></li><li class="nav-item nav-level-3"><a class="nav-link" href="#产生异常"><span class="nav-number">2.</span> <span class="nav-text">产生异常</span></a></li><li class="nav-item nav-level-3"><a class="nav-link" href="#异常的捕获"><span class="nav-number">3.</span> <span class="nav-text">异常的捕获</span></a></li><li class="nav-item nav-level-3"><a class="nav-link" href="#异常类及继承层次"><span class="nav-number">4.</span> <span class="nav-text">异常类及继承层次</span></a></li><li class="nav-item nav-level-3"><a class="nav-link" href="#BaseException及子类"><span class="nav-number">5.</span> <span class="nav-text">BaseException及子类</span></a><ol class="nav-child"><li class="nav-item nav-level-4"><a class="nav-link" href="#BaseException"><span class="nav-number">5.1.</span> <span class="nav-text">BaseException</span></a></li><li class="nav-item nav-level-4"><a class="nav-link" href="#SystemExit"><span class="nav-number">5.2.</span> <span class="nav-text">SystemExit</span></a></li><li class="nav-item nav-level-4"><a class="nav-link" href="#KeyboardIterrupt"><span class="nav-number">5.3.</span> <span class="nav-text">KeyboardIterrupt</span></a></li></ol></li><li class="nav-item nav-level-3"><a class="nav-link" href="#Exception及子类"><span class="nav-number">6.</span> <span class="nav-text">Exception及子类</span></a><ol class="nav-child"><li class="nav-item nav-level-4"><a class="nav-link" href="#SyntaxError-语法错误"><span class="nav-number">6.1.</span> <span class="nav-text">SyntaxError 语法错误</span></a></li><li class="nav-item nav-level-4"><a class="nav-link" href="#ArithmeticError"><span class="nav-number">6.2.</span> <span class="nav-text">ArithmeticError</span></a></li><li class="nav-item nav-level-4"><a class="nav-link" href="#LookupError"><span class="nav-number">6.3.</span> <span class="nav-text">LookupError</span></a></li><li class="nav-item nav-level-4"><a class="nav-link" href="#自定义异常"><span class="nav-number">6.4.</span> <span class="nav-text">自定义异常</span></a></li></ol></li><li class="nav-item nav-level-3"><a class="nav-link" href="#异常的捕获-1"><span class="nav-number">7.</span> <span class="nav-text">异常的捕获</span></a></li><li class="nav-item nav-level-3"><a class="nav-link" href="#as子句"><span class="nav-number">8.</span> <span class="nav-text">as子句</span></a></li><li class="nav-item nav-level-3"><a class="nav-link" href="#finally子句"><span class="nav-number">9.</span> <span class="nav-text">finally子句</span></a><ol class="nav-child"><li class="nav-item nav-level-4"><a class="nav-link" href="#finally-执行时机"><span class="nav-number">9.1.</span> <span class="nav-text">finally 执行时机</span></a></li></ol></li><li class="nav-item nav-level-3"><a class="nav-link" href="#异常的传递"><span class="nav-number">10.</span> <span class="nav-text">异常的传递</span></a></li><li class="nav-item nav-level-3"><a class="nav-link" href="#try嵌套"><span class="nav-number">11.</span> <span class="nav-text">try嵌套</span></a></li><li class="nav-item nav-level-3"><a class="nav-link" href="#异常的捕获时机"><span class="nav-number">12.</span> <span class="nav-text">异常的捕获时机</span></a></li><li class="nav-item nav-level-3"><a class="nav-link" href="#else子句"><span class="nav-number">13.</span> <span class="nav-text">else子句</span></a></li><li class="nav-item nav-level-3"><a class="nav-link" href="#总结"><span class="nav-number">14.</span> <span class="nav-text">总结</span></a></li><li class="nav-item nav-level-3"><a class="nav-link" href="#笔记"><span class="nav-number">15.</span> <span class="nav-text">笔记</span></a></li><li class="nav-item nav-level-3"><a class="nav-link" href="#总结-1"><span class="nav-number">16.</span> <span class="nav-text">总结</span></a><ol class="nav-child"><li class="nav-item nav-level-4"><a class="nav-link" href="#try语句的工作原理如下："><span class="nav-number">16.1.</span> <span class="nav-text">try语句的工作原理如下：</span></a></li><li class="nav-item nav-level-4"><a class="nav-link" href="#raise用法"><span class="nav-number">16.2.</span> <span class="nav-text">raise用法</span></a></li></ol></li></ol></div>
            

          </div>
        </section>
      <!--/noindex-->
      

      

    </div>
  </aside>


        
      </div>
    </main>

    <footer id="footer" class="footer">
      <div class="footer-inner">
        <div class="copyright">&copy; <span itemprop="copyrightYear">2020</span>
  <span class="with-love" id="animate">
    <i class="fa fa-user"></i>
  </span>
  <span class="author" itemprop="copyrightHolder">ruopu</span>

  

  

  <script async src="//busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js">
  </script>
  <span class="post-meta-divider">|</span>
  <span id="busuanzi_container_site_pv">
    本站总访问量: <span id="busuanzi_value_site_pv"></span>次
  </span>
</div>




  <div class="powered-by">由 <a class="theme-link" target="_blank" href="https://hexo.io">Hexo</a> 強力驅動 v3.7.1</div>



  <span class="post-meta-divider">|</span>



  <div class="theme-info">主題 – <a class="theme-link" target="_blank" href="https://theme-next.org">NexT.Gemini</a> v6.4.0</div>





        
<div class="busuanzi-count">
  <script async src="https://dn-lbstatics.qbox.me/busuanzi/2.3/busuanzi.pure.mini.js"></script>

  
    <span class="site-uv" title="訪客總數">
      <i class="fa fa-user"></i>
      <span class="busuanzi-value" id="busuanzi_value_site_uv"></span>
    </span>
  

  
    <span class="site-pv" title="總瀏覽次數">
      <i class="fa fa-eye"></i>
      <span class="busuanzi-value" id="busuanzi_value_site_pv"></span>
    </span>
  
</div>









        
      </div>
    </footer>

    
      <div class="back-to-top">
        <i class="fa fa-arrow-up"></i>
        
      </div>
    

    
	
    

    
  </div>

  

<script type="text/javascript">
  if (Object.prototype.toString.call(window.Promise) !== '[object Function]') {
    window.Promise = null;
  }
</script>


























  
  
    <script type="text/javascript" src="/lib/jquery/index.js?v=2.1.3"></script>
  

  
  
    <script type="text/javascript" src="/lib/velocity/velocity.min.js?v=1.2.1"></script>
  

  
  
    <script type="text/javascript" src="/lib/velocity/velocity.ui.min.js?v=1.2.1"></script>
  


  


  <script type="text/javascript" src="/js/src/utils.js?v=6.4.0"></script>

  <script type="text/javascript" src="/js/src/motion.js?v=6.4.0"></script>



  
  


  <script type="text/javascript" src="/js/src/affix.js?v=6.4.0"></script>

  <script type="text/javascript" src="/js/src/schemes/pisces.js?v=6.4.0"></script>



  
  <script type="text/javascript" src="/js/src/scrollspy.js?v=6.4.0"></script>
<script type="text/javascript" src="/js/src/post-details.js?v=6.4.0"></script>



  


  <script type="text/javascript" src="/js/src/bootstrap.js?v=6.4.0"></script>



  



  












  

  <script type="text/javascript">
    // Popup Window;
    var isfetched = false;
    var isXml = true;
    // Search DB path;
    var search_path = "search.xml";
    if (search_path.length === 0) {
      search_path = "search.xml";
    } else if (/json$/i.test(search_path)) {
      isXml = false;
    }
    var path = "/" + search_path;
    // monitor main search box;

    var onPopupClose = function (e) {
      $('.popup').hide();
      $('#local-search-input').val('');
      $('.search-result-list').remove();
      $('#no-result').remove();
      $(".local-search-pop-overlay").remove();
      $('body').css('overflow', '');
    }

    function proceedsearch() {
      $("body")
        .append('<div class="search-popup-overlay local-search-pop-overlay"></div>')
        .css('overflow', 'hidden');
      $('.search-popup-overlay').click(onPopupClose);
      $('.popup').toggle();
      var $localSearchInput = $('#local-search-input');
      $localSearchInput.attr("autocapitalize", "none");
      $localSearchInput.attr("autocorrect", "off");
      $localSearchInput.focus();
    }

    // search function;
    var searchFunc = function(path, search_id, content_id) {
      'use strict';

      // start loading animation
      $("body")
        .append('<div class="search-popup-overlay local-search-pop-overlay">' +
          '<div id="search-loading-icon">' +
          '<i class="fa fa-spinner fa-pulse fa-5x fa-fw"></i>' +
          '</div>' +
          '</div>')
        .css('overflow', 'hidden');
      $("#search-loading-icon").css('margin', '20% auto 0 auto').css('text-align', 'center');

      

      $.ajax({
        url: path,
        dataType: isXml ? "xml" : "json",
        async: true,
        success: function(res) {
          // get the contents from search data
          isfetched = true;
          $('.popup').detach().appendTo('.header-inner');
          var datas = isXml ? $("entry", res).map(function() {
            return {
              title: $("title", this).text(),
              content: $("content",this).text(),
              url: $("url" , this).text()
            };
          }).get() : res;
          var input = document.getElementById(search_id);
          var resultContent = document.getElementById(content_id);
          var inputEventFunction = function() {
            var searchText = input.value.trim().toLowerCase();
            var keywords = searchText.split(/[\s\-]+/);
            if (keywords.length > 1) {
              keywords.push(searchText);
            }
            var resultItems = [];
            if (searchText.length > 0) {
              // perform local searching
              datas.forEach(function(data) {
                var isMatch = false;
                var hitCount = 0;
                var searchTextCount = 0;
                var title = data.title.trim();
                var titleInLowerCase = title.toLowerCase();
                var content = data.content.trim().replace(/<[^>]+>/g,"");
                
                var contentInLowerCase = content.toLowerCase();
                var articleUrl = decodeURIComponent(data.url);
                var indexOfTitle = [];
                var indexOfContent = [];
                // only match articles with not empty titles
                if(title != '') {
                  keywords.forEach(function(keyword) {
                    function getIndexByWord(word, text, caseSensitive) {
                      var wordLen = word.length;
                      if (wordLen === 0) {
                        return [];
                      }
                      var startPosition = 0, position = [], index = [];
                      if (!caseSensitive) {
                        text = text.toLowerCase();
                        word = word.toLowerCase();
                      }
                      while ((position = text.indexOf(word, startPosition)) > -1) {
                        index.push({position: position, word: word});
                        startPosition = position + wordLen;
                      }
                      return index;
                    }

                    indexOfTitle = indexOfTitle.concat(getIndexByWord(keyword, titleInLowerCase, false));
                    indexOfContent = indexOfContent.concat(getIndexByWord(keyword, contentInLowerCase, false));
                  });
                  if (indexOfTitle.length > 0 || indexOfContent.length > 0) {
                    isMatch = true;
                    hitCount = indexOfTitle.length + indexOfContent.length;
                  }
                }

                // show search results

                if (isMatch) {
                  // sort index by position of keyword

                  [indexOfTitle, indexOfContent].forEach(function (index) {
                    index.sort(function (itemLeft, itemRight) {
                      if (itemRight.position !== itemLeft.position) {
                        return itemRight.position - itemLeft.position;
                      } else {
                        return itemLeft.word.length - itemRight.word.length;
                      }
                    });
                  });

                  // merge hits into slices

                  function mergeIntoSlice(text, start, end, index) {
                    var item = index[index.length - 1];
                    var position = item.position;
                    var word = item.word;
                    var hits = [];
                    var searchTextCountInSlice = 0;
                    while (position + word.length <= end && index.length != 0) {
                      if (word === searchText) {
                        searchTextCountInSlice++;
                      }
                      hits.push({position: position, length: word.length});
                      var wordEnd = position + word.length;

                      // move to next position of hit

                      index.pop();
                      while (index.length != 0) {
                        item = index[index.length - 1];
                        position = item.position;
                        word = item.word;
                        if (wordEnd > position) {
                          index.pop();
                        } else {
                          break;
                        }
                      }
                    }
                    searchTextCount += searchTextCountInSlice;
                    return {
                      hits: hits,
                      start: start,
                      end: end,
                      searchTextCount: searchTextCountInSlice
                    };
                  }

                  var slicesOfTitle = [];
                  if (indexOfTitle.length != 0) {
                    slicesOfTitle.push(mergeIntoSlice(title, 0, title.length, indexOfTitle));
                  }

                  var slicesOfContent = [];
                  while (indexOfContent.length != 0) {
                    var item = indexOfContent[indexOfContent.length - 1];
                    var position = item.position;
                    var word = item.word;
                    // cut out 100 characters
                    var start = position - 20;
                    var end = position + 80;
                    if(start < 0){
                      start = 0;
                    }
                    if (end < position + word.length) {
                      end = position + word.length;
                    }
                    if(end > content.length){
                      end = content.length;
                    }
                    slicesOfContent.push(mergeIntoSlice(content, start, end, indexOfContent));
                  }

                  // sort slices in content by search text's count and hits' count

                  slicesOfContent.sort(function (sliceLeft, sliceRight) {
                    if (sliceLeft.searchTextCount !== sliceRight.searchTextCount) {
                      return sliceRight.searchTextCount - sliceLeft.searchTextCount;
                    } else if (sliceLeft.hits.length !== sliceRight.hits.length) {
                      return sliceRight.hits.length - sliceLeft.hits.length;
                    } else {
                      return sliceLeft.start - sliceRight.start;
                    }
                  });

                  // select top N slices in content

                  var upperBound = parseInt('1');
                  if (upperBound >= 0) {
                    slicesOfContent = slicesOfContent.slice(0, upperBound);
                  }

                  // highlight title and content

                  function highlightKeyword(text, slice) {
                    var result = '';
                    var prevEnd = slice.start;
                    slice.hits.forEach(function (hit) {
                      result += text.substring(prevEnd, hit.position);
                      var end = hit.position + hit.length;
                      result += '<b class="search-keyword">' + text.substring(hit.position, end) + '</b>';
                      prevEnd = end;
                    });
                    result += text.substring(prevEnd, slice.end);
                    return result;
                  }

                  var resultItem = '';

                  if (slicesOfTitle.length != 0) {
                    resultItem += "<li><a href='" + articleUrl + "' class='search-result-title'>" + highlightKeyword(title, slicesOfTitle[0]) + "</a>";
                  } else {
                    resultItem += "<li><a href='" + articleUrl + "' class='search-result-title'>" + title + "</a>";
                  }

                  slicesOfContent.forEach(function (slice) {
                    resultItem += "<a href='" + articleUrl + "'>" +
                      "<p class=\"search-result\">" + highlightKeyword(content, slice) +
                      "...</p>" + "</a>";
                  });

                  resultItem += "</li>";
                  resultItems.push({
                    item: resultItem,
                    searchTextCount: searchTextCount,
                    hitCount: hitCount,
                    id: resultItems.length
                  });
                }
              })
            };
            if (keywords.length === 1 && keywords[0] === "") {
              resultContent.innerHTML = '<div id="no-result"><i class="fa fa-search fa-5x" /></div>'
            } else if (resultItems.length === 0) {
              resultContent.innerHTML = '<div id="no-result"><i class="fa fa-frown-o fa-5x" /></div>'
            } else {
              resultItems.sort(function (resultLeft, resultRight) {
                if (resultLeft.searchTextCount !== resultRight.searchTextCount) {
                  return resultRight.searchTextCount - resultLeft.searchTextCount;
                } else if (resultLeft.hitCount !== resultRight.hitCount) {
                  return resultRight.hitCount - resultLeft.hitCount;
                } else {
                  return resultRight.id - resultLeft.id;
                }
              });
              var searchResultList = '<ul class=\"search-result-list\">';
              resultItems.forEach(function (result) {
                searchResultList += result.item;
              })
              searchResultList += "</ul>";
              resultContent.innerHTML = searchResultList;
            }
          }

          if ('auto' === 'auto') {
            input.addEventListener('input', inputEventFunction);
          } else {
            $('.search-icon').click(inputEventFunction);
            input.addEventListener('keypress', function (event) {
              if (event.keyCode === 13) {
                inputEventFunction();
              }
            });
          }

          // remove loading animation
          $(".local-search-pop-overlay").remove();
          $('body').css('overflow', '');

          proceedsearch();
        }
      });
    }

    // handle and trigger popup window;
    $('.popup-trigger').click(function(e) {
      e.stopPropagation();
      if (isfetched === false) {
        searchFunc(path, 'local-search-input', 'local-search-result');
      } else {
        proceedsearch();
      };
    });

    $('.popup-btn-close').click(onPopupClose);
    $('.popup').click(function(e){
      e.stopPropagation();
    });
    $(document).on('keyup', function (event) {
      var shouldDismissSearchPopup = event.which === 27 &&
        $('.search-popup').is(':visible');
      if (shouldDismissSearchPopup) {
        onPopupClose();
      }
    });
  </script>





  

  

  

  

  
  

  

  

  

  

  

</body>
</html>
